/**
 * Alert, budget and delivery types, mirroring the backend's request and response bodies exactly
 * (snake_case; metric values, thresholds and money as decimal strings; every unknown value
 * `null`). Re-exported through `types.ts`.
 */

import type { User } from "./types";

/* ---------- Channels ---------- */

export type AlertChannelKind = "email" | "slack" | "webhook" | "pagerduty";

export type PagerDutySeverity = "critical" | "error" | "warning" | "info";

/** What a channel shows back of its settings. Secrets are never part of it. */
export type ChannelConfig =
  { to: string[] } | Record<string, never> | { url: string } | { severity: PagerDutySeverity };

export interface AlertChannel {
  id: string;
  org_id: string;
  kind: AlertChannelKind;
  name: string;
  config: ChannelConfig;
  /** Whether a secret is stored (Slack, webhook and PagerDuty). The secret itself is never sent. */
  has_secret: boolean;
  /** When a test notification last went through; null until one does. */
  verified_at: string | null;
  created_at: string;
  updated_at: string;
}

/** The answer of a create or a secret rotation: it carries a webhook's signing secret, once. */
export interface AlertChannelWithSecret extends AlertChannel {
  secret: string | null;
}

/**
 * A new channel. Slack and PagerDuty need `secret` (the incoming-webhook URL, the routing key);
 * email and webhook channels refuse it. A webhook's signing secret is generated by the server.
 */
export type AlertChannelCreate =
  | { kind: "email"; name: string; config: { to: string[] } }
  | { kind: "slack"; name: string; secret: string }
  | { kind: "webhook"; name: string; config: { url: string } }
  | { kind: "pagerduty"; name: string; secret: string; config?: { severity: PagerDutySeverity } };

/** A partial edit. The kind never changes; `rotate_secret` applies to webhooks only. */
export interface AlertChannelUpdate {
  name?: string;
  config?: ChannelConfig;
  /** Replaces a Slack URL or PagerDuty routing key. */
  secret?: string;
  rotate_secret?: boolean;
}

export interface ChannelTestResult {
  delivery_id: string;
  /** `pending` when a failure a retry might fix was left to the worker. */
  status: "sent" | "failed" | "pending";
  error: string | null;
}

/* ---------- Rules ---------- */

/** The kinds a person writes. `budget` rules belong to their budget and only appear in events. */
export type AlertRuleKind = "threshold" | "anomaly";

export type AlertEventRuleKind = AlertRuleKind | "budget";

/** The metrics a rule can measure. Budgets measure `spend` on their own. */
export type Metric = "error_rate" | "p95_ms" | "ttft_p95_ms" | "cost_usd" | "llm_calls" | "tokens";

export type Comparator = "gt" | "gte" | "lt" | "lte";

export interface AlertRuleFilters {
  environment?: string;
  provider?: string;
  model?: string;
}

export interface AlertRuleState {
  state: "ok" | "firing";
  /** When the rule entered `state`; for `ok` after a resolve, the resolve time. */
  since: string | null;
  /** The metric at the last evaluation; null when it was unknown. */
  last_value: string | null;
  last_evaluated_at: string | null;
}

export interface AlertRule {
  id: string;
  project_id: string;
  name: string;
  kind: AlertRuleKind;
  metric: Metric;
  comparator: Comparator;
  /** Null for an anomaly rule, whose line comes from its baseline. */
  threshold: string | null;
  window_minutes: number;
  /** Anomaly rules only. */
  baseline_windows: number | null;
  sensitivity: string | null;
  filters: AlertRuleFilters;
  cooldown_minutes: number;
  enabled: boolean;
  channel_ids: string[];
  /** While in the future the rule records events but notifies nobody. */
  muted_until: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  /** Null until the rule's first evaluation. */
  state: AlertRuleState | null;
}

/** What a rule measures and when it breaches. The preview's body. */
export interface AlertRuleDefinition {
  kind: AlertRuleKind;
  metric: Metric;
  comparator: Comparator;
  /** Threshold rules only; a decimal string, at least 0. */
  threshold?: string | null;
  /** 5 to 1440. */
  window_minutes: number;
  /** Anomaly rules only; 3 to 30. */
  baseline_windows?: number | null;
  /** Anomaly rules only; 0.5 to 5.0, 3.0 when omitted. */
  sensitivity?: string | null;
  filters?: AlertRuleFilters;
  /** 0 to 1440, 15 when omitted. */
  cooldown_minutes?: number;
  enabled?: boolean;
}

/** The preview's body: the definition alone. The server refuses `name` and `channel_ids` here. */
export type AlertRulePreviewInput = AlertRuleDefinition & { name?: never; channel_ids?: never };

/** The body of a create and of an edit. An edit sends the whole rule and replaces it. */
export interface AlertRuleInput extends AlertRuleDefinition {
  name: string;
  /** At most 10. */
  channel_ids?: string[];
}

export interface AlertPreviewPoint {
  /** The end of the window the value covers. */
  window_end: string;
  value: string | null;
  /** The line at that point; null for an anomaly rule without a baseline. */
  threshold: string | null;
}

export interface AlertPreview {
  points: AlertPreviewPoint[];
  /** True when some value is a percentile estimated from hourly histograms. */
  approximate: boolean;
}

/* ---------- Events ---------- */

export interface AlertEvent {
  id: string;
  rule_id: string;
  rule_name: string;
  rule_kind: AlertEventRuleKind;
  /** `firing` while open, `resolved` once `resolved_at` is set. */
  state: "firing" | "resolved";
  value: string | null;
  threshold: string | null;
  started_at: string;
  resolved_at: string | null;
  acknowledged_by: User | null;
  acknowledged_at: string | null;
}

export interface AlertEventQuery {
  rule_id?: string | undefined;
  state?: "firing" | "resolved" | undefined;
  limit?: number | undefined;
  cursor?: string | null | undefined;
}

/* ---------- Deliveries ---------- */

export type DeliveryStatus = "pending" | "sent" | "failed";

export interface DeliverySummary {
  /** `alert.fired`, `alert.resolved`, `budget.exceeded`, `insight.opened` or `test`. */
  event: string;
  /** Null for a test send, which has no event or rule. */
  event_id?: string | null;
  rule_id?: string | null;
  rule_name?: string | null;
  /** `insight.opened` only: the insight, its title and its project (channels are org-wide). */
  insight_id?: string | null;
  title?: string | null;
  /** Missing on rows queued before the project was kept. */
  project_id?: string | null;
}

export interface Delivery {
  id: string;
  kind: string;
  status: DeliveryStatus;
  attempts: number;
  next_attempt_at: string | null;
  last_error: string | null;
  created_at: string;
  summary: DeliverySummary | null;
}

export interface DeliveryQuery {
  status?: DeliveryStatus | undefined;
  limit?: number | undefined;
  cursor?: string | null | undefined;
}

/* ---------- Budgets ---------- */

export type BudgetScope = "project" | "gateway_key" | "user" | "model";

export type BudgetPeriod = "daily" | "monthly";

export type BudgetAction = "notify" | "block";

export interface BudgetState {
  /**
   * Spend so far in the current period; a decimal string. It is the budget rule's last value, so
   * it is null when the last evaluation could not measure spend.
   */
  spent_usd: string | null;
  period_start: string;
  resets_at: string;
  state: "ok" | "firing";
  last_evaluated_at: string;
}

export interface Budget {
  id: string;
  project_id: string;
  name: string;
  scope: BudgetScope;
  /** Null exactly when `scope` is `project`. */
  scope_id: string | null;
  period: BudgetPeriod;
  /** A decimal string, above 0. */
  amount_usd: string;
  action: BudgetAction;
  enabled: boolean;
  channel_ids: string[];
  /** Null until the budget's first evaluation. */
  state: BudgetState | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface BudgetInput {
  name: string;
  scope: BudgetScope;
  scope_id?: string | null;
  period: BudgetPeriod;
  amount_usd: string;
  action: BudgetAction;
  enabled?: boolean;
  channel_ids?: string[];
}

/**
 * A partial edit: only the fields sent change, and none may be null. `scope_id` changes only
 * together with `scope` (null for a `project` budget, required otherwise).
 */
export type BudgetUpdate = Partial<Omit<BudgetInput, "scope" | "scope_id">> &
  ({ scope?: never; scope_id?: never } | { scope: BudgetScope; scope_id?: string | null });
