"""Alert channels: where the organization's alerts are delivered.

Members read the list (`org:read`); admins and owners add, edit, delete and test channels
(`alerts:write`). A Slack URL or PagerDuty routing key is accepted in a request body and never
returned. A webhook's signing secret is generated by the server and returned once, by the create
and by an edit with `rotate_secret`; those responses are marked uncacheable, and neither route
takes an `Idempotency-Key`, which would keep the secret in the idempotency store. The test route
returns no secret, so it does take one.
"""

import uuid
from typing import Annotated

import structlog
from fastapi import APIRouter, Depends, Request, Response, status

from app.alerts import channel_test, queries, service
from app.alerts.channels.errors import (
    ChannelLimitError,
    ChannelNameTakenError,
    ChannelNotFoundError,
    EmailNotConfiguredError,
    RecipientNotMemberError,
)
from app.alerts.channels.urls import UnsafeUrlError
from app.alerts.schemas import InvalidChannelError
from app.api.deps import Access, ClockDep, DbSession, SettingsDep, client_ip, require
from app.api.schemas import (
    AlertChannelOut,
    AlertChannelSecretOut,
    ChannelCreate,
    ChannelTestOut,
    ChannelUpdate,
)
from app.core.crypto import CryptoNotConfigured
from app.core.egress import Resolver
from app.core.errors import FieldError, ProblemError, conflict, not_configured, not_found
from app.core.idempotency import idempotent
from app.core.permissions import Permission
from app.core.ratelimit import enforce_rate_limit
from app.core.security import mark_uncacheable
from app.db.models import AlertChannel

logger = structlog.get_logger(__name__)

router = APIRouter(prefix="/orgs/{org_id}/alert-channels", tags=["alerts"])

ChannelReader = Annotated[Access, Depends(require(Permission.ORG_READ))]
ChannelWriter = Annotated[Access, Depends(require(Permission.ALERTS_WRITE))]
IdempotentChannelWriter = Annotated[Access, Depends(idempotent(require(Permission.ALERTS_WRITE)))]

NEEDS_KEYS = (
    "Slack, webhook and PagerDuty channels keep their secret encrypted with a server key that "
    "isn't set. Ask your administrator to set CREDENTIALS_KEYS."
)

CHANNEL_ERRORS = (
    CryptoNotConfigured,
    ChannelNotFoundError,
    ChannelNameTakenError,
    ChannelLimitError,
    RecipientNotMemberError,
    UnsafeUrlError,
    InvalidChannelError,
    EmailNotConfiguredError,
)

NEEDS_EMAIL = (
    "Email alerts need an email provider, and none is configured. "
    "Ask your administrator to set EMAIL_PROVIDER."
)


def _channel_problem(error: Exception) -> ProblemError:
    """The problem response for an error the channel service raises."""
    if isinstance(error, CryptoNotConfigured):
        return not_configured(NEEDS_KEYS)
    if isinstance(error, EmailNotConfiguredError):
        return not_configured(NEEDS_EMAIL)
    if isinstance(error, ChannelNotFoundError):
        return not_found()
    if isinstance(error, ChannelNameTakenError):
        return conflict(
            "CHANNEL_NAME_TAKEN", "A channel with this name already exists in this organization."
        )
    if isinstance(error, ChannelLimitError):
        return ProblemError(
            422, "LIMIT_EXCEEDED", f"An organization can have at most {error.limit} channels."
        )
    if isinstance(error, RecipientNotMemberError):
        listed = ", ".join(error.addresses)
        return ProblemError(
            422,
            "RECIPIENT_NOT_MEMBER",
            "Alert emails go only to members of this organization with a verified email.",
            errors=[FieldError(field="config.to", message=f"Not a verified member: {listed}")],
        )
    if isinstance(error, UnsafeUrlError):
        return ProblemError(
            422,
            "UNSAFE_URL",
            "The webhook URL is not allowed.",
            errors=[FieldError(field="config.url", message=str(error))],
        )
    if isinstance(error, InvalidChannelError):
        return ProblemError(422, "VALIDATION_ERROR", "The request is invalid.", errors=error.errors)
    raise error


def _resolver(request: Request) -> Resolver | None:
    # A test seam: `create_app(gateway_resolver=...)` fakes the DNS that URLs are vetted against.
    resolver: Resolver | None = getattr(request.app.state, "egress_resolver", None)
    return resolver


def _channel_out(channel: AlertChannel) -> AlertChannelOut:
    return AlertChannelOut.model_validate(channel)


def _secret_out(channel: AlertChannel, secret: str | None) -> AlertChannelSecretOut:
    return AlertChannelSecretOut(**_channel_out(channel).model_dump(), secret=secret)


@router.get("", response_model=list[AlertChannelOut], summary="List alert channels")
async def list_channels(
    org_id: uuid.UUID, access: ChannelReader, db: DbSession
) -> list[AlertChannelOut]:
    """By name. Never includes a secret."""
    return [_channel_out(channel) for channel in await queries.list_channels(db, access.org.id)]


@router.post(
    "",
    status_code=status.HTTP_201_CREATED,
    response_model=AlertChannelSecretOut,
    summary="Add an alert channel",
)
async def create_channel(
    org_id: uuid.UUID,
    body: ChannelCreate,
    request: Request,
    response: Response,
    access: ChannelWriter,
    db: DbSession,
    settings: SettingsDep,
    clock: ClockDep,
) -> AlertChannelSecretOut:
    """Store a channel. A webhook channel's response carries its signing `secret`, once.

    `409 NOT_CONFIGURED` for Slack, webhook and PagerDuty without CREDENTIALS_KEYS;
    `409 CHANNEL_NAME_TAKEN`; `422 LIMIT_EXCEEDED` past 20 channels; `422 RECIPIENT_NOT_MEMBER`;
    `422 UNSAFE_URL` for a webhook URL that is not `https://` or resolves to a private address.
    """
    try:
        channel, secret = await service.create_channel(
            db,
            access.org.id,
            access.user_id,
            body,
            settings=settings,
            now=clock(),
            ip=client_ip(request),
            resolver=_resolver(request),
        )
    except CHANNEL_ERRORS as error:
        raise _channel_problem(error) from None
    await db.commit()
    logger.info(
        "alert_channel_created",
        org_id=str(access.org.id),
        channel_id=str(channel.id),
        kind=channel.kind.value,
    )
    mark_uncacheable(response)
    return _secret_out(channel, secret)


@router.get("/{channel_id}", response_model=AlertChannelOut, summary="Get an alert channel")
async def get_channel(
    org_id: uuid.UUID, channel_id: uuid.UUID, access: ChannelReader, db: DbSession
) -> AlertChannelOut:
    channel = await queries.get_channel(db, access.org.id, channel_id)
    if channel is None:
        raise not_found()
    return _channel_out(channel)


@router.patch(
    "/{channel_id}", response_model=AlertChannelSecretOut, summary="Edit an alert channel"
)
async def update_channel(
    org_id: uuid.UUID,
    channel_id: uuid.UUID,
    body: ChannelUpdate,
    request: Request,
    response: Response,
    access: ChannelWriter,
    db: DbSession,
    settings: SettingsDep,
    clock: ClockDep,
) -> AlertChannelSecretOut:
    """Change the name, config or secret. The kind never changes.

    `rotate_secret` (webhooks only) generates a new signing secret, returned once. A new config
    or secret clears `verified_at`. Errors as for the create.
    """
    try:
        channel, secret = await service.update_channel(
            db,
            access.org.id,
            channel_id,
            access.user_id,
            body,
            settings=settings,
            now=clock(),
            ip=client_ip(request),
            resolver=_resolver(request),
        )
    except CHANNEL_ERRORS as error:
        raise _channel_problem(error) from None
    await db.commit()
    logger.info("alert_channel_updated", org_id=str(access.org.id), channel_id=str(channel_id))
    mark_uncacheable(response)
    return _secret_out(channel, secret)


@router.delete(
    "/{channel_id}", status_code=status.HTTP_204_NO_CONTENT, summary="Delete an alert channel"
)
async def delete_channel(
    org_id: uuid.UUID, channel_id: uuid.UUID, request: Request, access: ChannelWriter, db: DbSession
) -> None:
    """Rules that name the channel keep its id and skip it until they are edited."""
    try:
        await service.delete_channel(
            db, access.org.id, channel_id, access.user_id, ip=client_ip(request)
        )
    except CHANNEL_ERRORS as error:
        raise _channel_problem(error) from None
    await db.commit()
    logger.info("alert_channel_deleted", org_id=str(access.org.id), channel_id=str(channel_id))


@router.post(
    "/{channel_id}/test", response_model=ChannelTestOut, summary="Send a test notification"
)
async def send_channel_test(
    org_id: uuid.UUID,
    channel_id: uuid.UUID,
    request: Request,
    access: IdempotentChannelWriter,
    db: DbSession,
    settings: SettingsDep,
    clock: ClockDep,
) -> ChannelTestOut:
    """Deliver a test now. A failing channel is a `200` with `status: "failed"` and the error.

    `pending` when a failure a retry might fix left it to the worker. `sent` records the channel
    as verified. At most 10 tests per channel an hour (`429 RATE_LIMITED`). An email channel
    while no email provider is configured is `409 NOT_CONFIGURED`.
    """
    # Before the limiter, so a token is only ever taken for a channel of the caller's own org.
    if await queries.get_channel(db, access.org.id, channel_id) is None:
        raise not_found()
    await enforce_rate_limit(
        request,
        channel_test.CHANNEL_TEST_LIMITER,
        channel_test.limiter_key(channel_id),
        scope="alert_test",
        detail="This channel was tested 10 times in the last hour. Try again later.",
    )
    try:
        result = await channel_test.send_test(
            db,
            request.app.state.session_factory,
            access.org,
            channel_id,
            access.user_id,
            settings=settings,
            clock=clock,
            ip=client_ip(request),
        )
    except CHANNEL_ERRORS as error:
        raise _channel_problem(error) from None
    return ChannelTestOut(delivery_id=result.delivery_id, status=result.status, error=result.error)
