"""What an alert channel is created and edited from. Pure: no database, no I/O.

A channel's `config` holds the settings that may be shown back (recipients, a webhook URL, a
PagerDuty severity); its secret (a Slack incoming-webhook URL, a PagerDuty routing key) is sent
separately as `secret` and never returned. A webhook's signing secret is generated by the server.
The bounds match migration 0301 and the phase's limits: names of 1 to 80 characters, 1 to 10
email recipients. Unknown fields are rejected.

Validation messages never repeat a secret's value.
"""

from typing import Annotated, Any, Literal

from pydantic import (
    AfterValidator,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    SecretStr,
    StringConstraints,
    ValidationError,
    ValidationInfo,
    field_validator,
)
from pydantic_core import PydanticCustomError

from app.core.errors import FieldError
from app.db.models import AlertChannelKind

MAX_RECIPIENTS = 10
MAX_URL_LENGTH = 2048
SLACK_URL_PREFIX = "https://hooks.slack.com/"
ROUTING_KEY_LENGTH = 32

ChannelName = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=80)]


def _lower_unique(addresses: list[str]) -> list[str]:
    """Lower-cased, without repeats, in the order given."""
    return list(dict.fromkeys(address.lower() for address in addresses))


Recipients = Annotated[
    list[EmailStr],
    Field(min_length=1, max_length=MAX_RECIPIENTS),
    AfterValidator(_lower_unique),
]


def check_slack_url(value: SecretStr) -> SecretStr:
    """A Slack incoming-webhook URL: `https://hooks.slack.com/...`, trimmed, no spaces."""
    url = value.get_secret_value().strip()
    if len(url) > MAX_URL_LENGTH:
        raise ValueError(f"must be at most {MAX_URL_LENGTH} characters")
    if not url.startswith(SLACK_URL_PREFIX) or len(url) == len(SLACK_URL_PREFIX):
        raise ValueError(f"must be a Slack incoming webhook URL starting with {SLACK_URL_PREFIX}")
    if not all("!" <= character <= "~" for character in url):
        raise ValueError("must contain only visible ASCII characters, without spaces")
    return SecretStr(url)


def check_routing_key(value: SecretStr) -> SecretStr:
    """A PagerDuty Events API v2 routing key: 32 letters and digits, trimmed."""
    key = value.get_secret_value().strip()
    if len(key) != ROUTING_KEY_LENGTH or not (key.isascii() and key.isalnum()):
        raise ValueError(f"must be a routing key of {ROUTING_KEY_LENGTH} letters and digits")
    return SecretStr(key)


# A secret as sent. The bound only stops an oversized body early; the kind's check (above)
# applies the real rules.
ClientSecret = Annotated[SecretStr, Field(max_length=2 * MAX_URL_LENGTH)]
PagerDutySeverity = Literal["critical", "error", "warning", "info"]


class EmailConfig(BaseModel):
    """Who gets the email: 1 to 10 addresses, stored lower-cased and without repeats."""

    model_config = ConfigDict(extra="forbid")

    to: Recipients


class SlackConfig(BaseModel):
    """Nothing to configure: the incoming-webhook URL is the channel's secret."""

    model_config = ConfigDict(extra="forbid")


class WebhookConfig(BaseModel):
    """Where the signed POST goes. The URL rules that need settings or DNS are in `urls.py`."""

    model_config = ConfigDict(extra="forbid")

    url: Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=2048)]


class PagerDutyConfig(BaseModel):
    """The severity PagerDuty shows on events from this channel."""

    model_config = ConfigDict(extra="forbid")

    severity: PagerDutySeverity = "error"


ChannelConfig = EmailConfig | SlackConfig | WebhookConfig | PagerDutyConfig

CONFIG_MODELS: dict[AlertChannelKind, type[ChannelConfig]] = {
    AlertChannelKind.EMAIL: EmailConfig,
    AlertChannelKind.SLACK: SlackConfig,
    AlertChannelKind.WEBHOOK: WebhookConfig,
    AlertChannelKind.PAGERDUTY: PagerDutyConfig,
}

# The kinds whose secret the client sends. A webhook's secret is generated; email has none.
CLIENT_SECRET_CHECKS = {
    AlertChannelKind.SLACK: check_slack_url,
    AlertChannelKind.PAGERDUTY: check_routing_key,
}


def _kind_of(info: ValidationInfo) -> AlertChannelKind:
    kind = info.data.get("kind")
    if not isinstance(kind, AlertChannelKind):
        raise PydanticCustomError("needs_kind", "must be sent together with a valid kind")
    return kind


class ChannelCreate(BaseModel):
    """A new channel. `config` and `secret` are validated for the `kind` sent with them.

    Slack and PagerDuty need `secret` (the incoming-webhook URL, the routing key); email and
    webhook channels refuse it. An omitted `config` is the kind's default, which only Slack and
    PagerDuty have. Errors come out under `config.<field>` and `secret`.
    """

    model_config = ConfigDict(extra="forbid")

    kind: AlertChannelKind
    name: ChannelName
    config: ChannelConfig = Field(default_factory=dict, validate_default=True)
    secret: ClientSecret | None = Field(default=None, validate_default=True)

    @field_validator("config", mode="before")
    @classmethod
    def _config_for_kind(cls, value: Any, info: ValidationInfo) -> ChannelConfig:
        # A ValidationError raised here is merged into the field's errors, so its locations
        # come out as `config.<field>`.
        return CONFIG_MODELS[_kind_of(info)].model_validate(value)

    @field_validator("secret")
    @classmethod
    def _secret_for_kind(cls, value: SecretStr | None, info: ValidationInfo) -> SecretStr | None:
        kind = _kind_of(info)
        check = CLIENT_SECRET_CHECKS.get(kind)
        if check is None:
            if value is not None:
                raise ValueError(f"is not accepted for a {kind.value} channel")
            return None
        if value is None:
            raise ValueError(f"is required for a {kind.value} channel")
        return check(value)


class ChannelUpdate(BaseModel):
    """A partial edit: only the fields sent change. A channel's kind never changes.

    `config` is validated against the channel's kind (`parse_config`), so it is taken as an
    object here. `secret` replaces a Slack URL or PagerDuty routing key; `rotate_secret`
    generates a new webhook signing secret, returned once.
    """

    model_config = ConfigDict(extra="forbid")

    name: ChannelName | None = None
    config: dict[str, Any] | None = None
    secret: ClientSecret | None = None
    rotate_secret: bool = False

    @field_validator("name", "config", "secret")
    @classmethod
    def _not_null(cls, value: Any) -> Any:
        # Runs only for a value that was sent: an absent field keeps its default untouched.
        if value is None:
            raise ValueError("must not be null")
        return value


class InvalidChannelError(ValueError):
    """A request that breaks a channel rule. `errors` name the fields; no value is quoted."""

    def __init__(self, errors: list[FieldError]) -> None:
        super().__init__("; ".join(error["field"] for error in errors))
        self.errors = errors


def field_problem(field: str, message: str) -> InvalidChannelError:
    return InvalidChannelError([FieldError(field=field, message=message)])


def parse_config(kind: AlertChannelKind, raw: dict[str, Any]) -> ChannelConfig:
    """`raw` as the config of a `kind` channel, or `InvalidChannelError` under `config.`."""
    try:
        return CONFIG_MODELS[kind].model_validate(raw)
    except ValidationError as error:
        raise InvalidChannelError(
            [
                FieldError(
                    field=".".join(["config", *(str(part) for part in item["loc"])]),
                    message=item["msg"],
                )
                for item in error.errors()
            ]
        ) from None


def parse_secret(kind: AlertChannelKind, secret: SecretStr) -> SecretStr:
    """A client-sent secret checked for `kind`, or `InvalidChannelError` on `secret`."""
    check = CLIENT_SECRET_CHECKS.get(kind)
    if check is None:
        raise field_problem("secret", f"is not accepted for a {kind.value} channel")
    try:
        return check(secret)
    except ValueError as error:
        raise field_problem("secret", str(error)) from None
