"""Add trace exports.

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-09

An export is one request to write a project's traces, filtered by the trace-list filters, to a
file in object storage. The row is the request and its progress: it is inserted `queued` together
with the `create_export` job, the job moves it to `running`, then to `done` (with the object's
key, size and row count) or `failed` (with a stable `error_code`). Seven days after completion
cleanup deletes the object and sets `expired`.

Choices worth knowing about:

* The ids are UUIDv7 generated by the application, like every other public id, so the column
  has no default.
* The CHECK constraints keep the states honest: a `done` row always says where its file is and
  how big it is, and a `failed` row always says why. `expired` rows have no `storage_key`: the
  object is gone.
* `created_by` is `ON DELETE SET NULL`: deleting a person keeps the export history of the
  project. `project_id` cascades, so deleting a project removes its export rows. Their files
  are not reached through the rows: the deletion queues a `purge_project_objects` job in the
  same transaction, which deletes everything under the project's export prefix.
* The list index serves `GET /projects/{id}/exports` (newest first, keyset on `created_at, id`).
  The partial index serves the cleanup job, which looks for finished exports past their expiry
  across all projects; it holds only `done` rows, which are few.
* Row-level security is the same policy pair as `traces`: a row is visible when it belongs to
  the project bound to the transaction, or when worker code opted into bypass.

Downgrade drops the table and the three enum types. Objects already written to storage are not
touched.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE TYPE export_kind AS ENUM ('traces')")
    op.execute("CREATE TYPE export_format AS ENUM ('jsonl', 'csv')")
    op.execute(
        "CREATE TYPE export_status AS ENUM ('queued', 'running', 'done', 'failed', 'expired')"
    )
    op.execute(
        """
        CREATE TABLE exports (
            id           uuid PRIMARY KEY,
            project_id   uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            kind         export_kind NOT NULL DEFAULT 'traces',
            format       export_format NOT NULL,
            filters      jsonb NOT NULL,
            status       export_status NOT NULL DEFAULT 'queued',
            storage_key  text,
            size_bytes   bigint CHECK (size_bytes >= 0),
            row_count    bigint CHECK (row_count >= 0),
            error_code   text,
            created_by   uuid REFERENCES users (id) ON DELETE SET NULL,
            created_at   timestamptz NOT NULL DEFAULT now(),
            completed_at timestamptz,
            expires_at   timestamptz,
            CONSTRAINT exports_done_has_file CHECK (
                status <> 'done' OR (
                    storage_key IS NOT NULL AND size_bytes IS NOT NULL
                    AND row_count IS NOT NULL AND completed_at IS NOT NULL
                    AND expires_at IS NOT NULL
                )
            ),
            CONSTRAINT exports_failed_has_error CHECK (
                status <> 'failed' OR error_code IS NOT NULL
            )
        )
        """
    )
    op.execute(
        "CREATE INDEX exports_project_created_idx ON exports (project_id, created_at DESC, id DESC)"
    )
    op.execute("CREATE INDEX exports_created_by_idx ON exports (created_by)")
    op.execute(
        "CREATE INDEX exports_done_expires_idx ON exports (expires_at) WHERE status = 'done'"
    )

    op.execute("ALTER TABLE exports ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE exports FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY exports_project_isolation ON exports
            USING (project_id = NULLIF(current_setting('app.project_id', true), '')::uuid)
            WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), '')::uuid)
        """
    )
    op.execute(
        """
        CREATE POLICY exports_worker_bypass ON exports
            USING (current_setting('app.bypass_rls', true) = 'on')
            WITH CHECK (current_setting('app.bypass_rls', true) = 'on')
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS exports")
    for enum_type in ("export_status", "export_format", "export_kind"):
        op.execute(f"DROP TYPE IF EXISTS {enum_type}")
