"""Add provider credentials, and allow the Phase 2 audit actions.

Revision ID: 0200
Revises: 0017
Create Date: 2026-10-09

A provider credential is an organization's API key for OpenAI, Anthropic or an OpenAI-compatible
server, kept so the gateway can call the provider on the organization's behalf. The key has to be
read back in clear text, so it is sealed in the application (AES-256-GCM, `app.core.crypto`) and
the table only ever holds the sealed bytes and the id of the key that sealed them.

Choices worth knowing about:

* The ids are UUIDv7 generated by the application, like every other public id, so the column
  has no default.
* The table is scoped to an organization, not a project, so it has no row-level security: every
  query filters by `org_id` (`app.gateway.queries`), and an authorization-matrix test covers the
  routes. `org_id` cascades, so deleting an organization deletes its credentials.
* `UNIQUE (org_id, name)` makes a name pick out one credential in its organization (a duplicate
  is `409 CREDENTIAL_NAME_TAKEN`). Its index leads with `org_id`, so it also serves the foreign
  key and the per-organization list; a separate `org_id` index would duplicate it.
* `created_by` is `ON DELETE SET NULL`: removing a person keeps the credentials they added.
* The CHECK ties `base_url` to the provider: an OpenAI-compatible server needs one, and the two
  fixed providers never have one, so a row cannot send OpenAI's key to some other host.
* `last_checked_at` and `last_error` record the most recent check (`POST .../check`); both are
  NULL for a credential that was never checked. `last_error` is a short status line such as
  `401 Unauthorized`, never a provider's response body.

`audit_events.action` is a CHECK over a fixed list, so it is dropped and added again with the
sixteen Phase 2 actions, as in 0009. The migration is one transaction; `audit_events` stays locked
while the new constraint scans its rows, which is acceptable for a table of small, infrequent rows.

Downgrade deletes the audit events that use the new actions, which the older constraint would
reject, restores the previous list, and drops the table and its enum type. The sealed keys are
gone with it.
"""

from collections.abc import Sequence

from alembic import op

PREVIOUS_AUDIT_ACTIONS = (
    "org.create",
    "member.add",
    "member.role_change",
    "member.remove",
    "invite.create",
    "invite.revoke",
    "invite.accept",
    "project.create",
    "project.update",
    "key.create",
    "key.revoke",
    "user.password_reset",
    "user.oauth_link",
    "user.oauth_unlink",
    "user.totp_enable",
    "user.totp_disable",
    "org.update",
    "project.delete",
)
NEW_AUDIT_ACTIONS = (
    "credential.create",
    "credential.rotate",
    "credential.delete",
    "gateway_route.create",
    "gateway_route.update",
    "gateway_route.revert",
    "gateway_route.delete",
    "gateway_key.create",
    "gateway_key.update",
    "gateway_key.revoke",
    "fault_profile.create",
    "fault_profile.update",
    "fault_profile.delete",
    "price_override.create",
    "price_override.delete",
    "gateway_cache.purge",
)

revision: str = "0200"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE TYPE provider_kind AS ENUM ('openai', 'anthropic', 'openai_compatible')")
    op.execute(
        """
        CREATE TABLE provider_credentials (
            id              uuid PRIMARY KEY,
            org_id          uuid NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
            provider        provider_kind NOT NULL,
            name            text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
            base_url        text CHECK (char_length(base_url) <= 2048),
            ciphertext      bytea NOT NULL,
            key_id          text NOT NULL,
            created_by      uuid REFERENCES users (id) ON DELETE SET NULL,
            created_at      timestamptz NOT NULL DEFAULT now(),
            rotated_at      timestamptz,
            last_used_at    timestamptz,
            last_checked_at timestamptz,
            last_error      text CHECK (char_length(last_error) <= 200),
            CONSTRAINT provider_credentials_org_name_key UNIQUE (org_id, name),
            CONSTRAINT provider_credentials_base_url_matches_provider CHECK (
                (provider = 'openai_compatible') = (base_url IS NOT NULL)
            )
        )
        """
    )
    op.execute(
        "CREATE INDEX provider_credentials_created_by_idx ON provider_credentials (created_by)"
    )
    _set_audit_actions((*PREVIOUS_AUDIT_ACTIONS, *NEW_AUDIT_ACTIONS))


def downgrade() -> None:
    listed = ", ".join(f"'{action}'" for action in NEW_AUDIT_ACTIONS)
    op.execute(f"DELETE FROM audit_events WHERE action IN ({listed})")
    _set_audit_actions(PREVIOUS_AUDIT_ACTIONS)
    op.execute("DROP TABLE IF EXISTS provider_credentials")
    op.execute("DROP TYPE IF EXISTS provider_kind")


def _set_audit_actions(actions: tuple[str, ...]) -> None:
    listed = ", ".join(f"'{action}'" for action in actions)
    op.execute("ALTER TABLE audit_events DROP CONSTRAINT audit_events_action_check")
    op.execute(
        "ALTER TABLE audit_events ADD CONSTRAINT audit_events_action_check "
        f"CHECK (action IN ({listed}))"
    )
