"""Add gateway routes and their version history.

Revision ID: 0201
Revises: 0200
Create Date: 2026-10-09

A gateway route decides which provider credentials serve a gateway call and what happens when
one fails: its `config` holds the targets, the retry and fallback policies and the time budget,
validated by `app.gateway.route_config.RouteConfig` before it is stored. Every save of a route,
its creation included, appends the config to `gateway_route_versions` under the new version
number, so an edit is auditable and a revert can save an old config again as a new version.

Choices worth knowing about:

* The ids are UUIDv7 generated by the application, like every other public id, so the column
  has no default. `project_id` cascades, so deleting a project deletes its routes, and deleting
  a route deletes its history.
* `UNIQUE (project_id, name)` makes a name pick out one route in its project (a duplicate is
  `409 ROUTE_NAME_TAKEN`). Its index leads with `project_id`, so it also serves the foreign key
  and the per-project list; a separate `project_id` index would duplicate it.
* The partial unique index on `(project_id) WHERE is_default` allows at most one default route
  per project: the one a gateway key uses when it names no route.
* `version` counts saves from 1. The service bumps it with `UPDATE ... WHERE version = :expected`,
  so of two concurrent edits from the same version one is `409 ROUTE_VERSION_CONFLICT`.
* `gateway_route_versions` carries `project_id` as well, so its row-level security policy is the
  same column test as every other project-scoped table, with no join. The composite foreign key
  to `gateway_routes (id, project_id)` keeps it equal to the route's project; the extra unique
  constraint on `(id, project_id)` exists only to be that key's target.
* `updated_by` is `ON DELETE SET NULL` in both tables: removing a person keeps the routes and
  the history they wrote.
* Row-level security on both tables is the policy pair every project-scoped table has, in the
  InitPlan form of 0017: a row is visible when it belongs to the project bound to the
  transaction, or when worker code opted into bypass.

Downgrade drops both tables. Route configs and their history are gone with them.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0201"
down_revision: str | None = "0200"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = ("gateway_routes", "gateway_route_versions")

PROJECT_EXPRESSION = (
    "project_id = (SELECT NULLIF(current_setting('app.project_id', true), '')::uuid)"
)
BYPASS_EXPRESSION = "(SELECT current_setting('app.bypass_rls', true)) = 'on'"


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE gateway_routes (
            id          uuid PRIMARY KEY,
            project_id  uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            name        text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
            is_default  boolean NOT NULL DEFAULT false,
            config      jsonb NOT NULL CHECK (jsonb_typeof(config) = 'object'),
            version     integer NOT NULL DEFAULT 1 CHECK (version >= 1),
            updated_by  uuid REFERENCES users (id) ON DELETE SET NULL,
            created_at  timestamptz NOT NULL DEFAULT now(),
            updated_at  timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT gateway_routes_project_name_key UNIQUE (project_id, name),
            CONSTRAINT gateway_routes_id_project_key UNIQUE (id, project_id)
        )
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX gateway_routes_one_default_idx ON gateway_routes (project_id) "
        "WHERE is_default"
    )
    op.execute("CREATE INDEX gateway_routes_updated_by_idx ON gateway_routes (updated_by)")

    op.execute(
        """
        CREATE TABLE gateway_route_versions (
            route_id    uuid NOT NULL,
            version     integer NOT NULL CHECK (version >= 1),
            project_id  uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            config      jsonb NOT NULL CHECK (jsonb_typeof(config) = 'object'),
            updated_by  uuid REFERENCES users (id) ON DELETE SET NULL,
            created_at  timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (route_id, version),
            CONSTRAINT gateway_route_versions_route_fkey FOREIGN KEY (route_id, project_id)
                REFERENCES gateway_routes (id, project_id) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        "CREATE INDEX gateway_route_versions_project_idx ON gateway_route_versions (project_id)"
    )
    op.execute(
        "CREATE INDEX gateway_route_versions_updated_by_idx ON gateway_route_versions (updated_by)"
    )

    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_project_isolation ON {table} "
            f"USING ({PROJECT_EXPRESSION}) WITH CHECK ({PROJECT_EXPRESSION})"
        )
        op.execute(
            f"CREATE POLICY {table}_worker_bypass ON {table} "
            f"USING ({BYPASS_EXPRESSION}) WITH CHECK ({BYPASS_EXPRESSION})"
        )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS gateway_route_versions")
    op.execute("DROP TABLE IF EXISTS gateway_routes")
