"""Add gateway keys, their per-minute usage, and the gateway key a span came through.

Revision ID: 0202
Revises: 0201
Create Date: 2026-10-09

A gateway key (`spl_gw_…`) is what an application sends to the LLM gateway instead of a provider
key. It belongs to one project, sends its calls through one route, and is the unit of limits and
attribution: requests and tokens per minute, the models it may ask for, the tags its traces get
and whether identical calls are served from the cache. Like a project API key, only the first
part (`prefix`) is stored in clear and used to find the row; the secret is kept as its SHA-256.

`gateway_key_minutes` counts each key's requests and tokens per clock minute; the tokens-per-
minute limit reads the current minute's row. `spans.source_key_id` records which gateway key a
call came through, for budgets and detectors that work per key. Native ingestion leaves it NULL.

Choices worth knowing about:

* The ids are UUIDv7 generated by the application, so the columns have no default. `project_id`
  cascades, so deleting a project deletes its keys and their minutes.
* `route_id` references `gateway_routes (id, project_id)`, so a key can only use a route of its
  own project, and the reference is `ON DELETE RESTRICT`: the route service answers `409
  ROUTE_IN_USE` before deleting a route that an active key uses, and the constraint is the net
  under it. Deleting a project still works: the routes and the keys both cascade from it, and
  the restrict check runs after the cascades of the same statement have removed the keys.
* `route_id` is NULL only for a revoked key (the CHECK). A revoked key keeps its route until that
  route is deleted, when the route service clears it; a revoked key never blocks a deletion,
  and it stays in the table so the spans it was used for keep their attribution.
* `prefix` is unique across every project: the gateway finds the key by it before it knows the
  project. The limits, the array sizes and the cache TTL have CHECKs matching the API's bounds
  (each tag's own length is checked by the API; a CHECK cannot look inside an array cheaply).
  `allowed_models` empty means any model. There is no unique name: two keys may share a name.
* `UNIQUE (id, project_id)` exists only to be the target of the composite key from
  `gateway_key_minutes`, which repeats `project_id` so its row-level security policy is the same
  column test as every other project-scoped table. The minute's `tokens` is `bigint`: it adds up
  every call in the minute, and a key without a tokens limit has no upper bound.
* Row-level security on both tables is the policy pair every project-scoped table has, in the
  InitPlan form of 0017. `gateway_keys` has a third policy, for `SELECT` only: a row is visible
  when its `prefix` equals the transaction-local setting `app.gateway_key_prefix`. The gateway
  has to find a presented key before it knows the key's project, and request code never sets
  the bypass flag. So `app.gateway.key_context.load_key_context` sets that one prefix, reads the
  row, clears the setting and binds the key's project for the rest of the request. The setting
  shows at most the one row whose prefix was presented, never another project's keys, and it
  allows no writes; unset, it is NULL and the policy shows nothing.
* `spans.source_key_id` is a plain `uuid` without a foreign key: every span insert would pay a
  lookup, adding the constraint would scan the whole table, and `spans` is to be partitioned
  later. Adding a nullable column without a default changes only the catalog, under a lock held
  for milliseconds that the migration waits at most 5 seconds for. Its index is
  partial, `WHERE source_key_id IS NOT NULL`, so spans from native ingestion never enter it.
  A second partial index, `(project_id, started_at)` with the same predicate, serves the gateway
  overview, which reads every key's calls of a time window and so cannot use the first one's
  key-first order for a range scan.
* The column and the index on `spans` come first, outside the migration's transaction, the way
  0016 builds its index: `CREATE INDEX CONCURRENTLY` lets writes to `spans` continue while the
  index is built, and it cannot run in a transaction, hence `autocommit_block()`. Both steps are
  safe to run again (`IF NOT EXISTS`, and an INVALID leftover of an interrupted build is dropped
  first). Doing them first means a failure there leaves nothing else half done; the two new
  tables are created afterwards, in one transaction with the version stamp.

Downgrade drops both tables, then the index (concurrently) and the column. The keys stop
working, and the spans lose the record of which key they came through.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0202"
down_revision: str | None = "0201"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = ("gateway_keys", "gateway_key_minutes")
LOCK_TIMEOUT = "5s"
SPANS_INDEX = "spans_project_source_key_started_idx"
SPANS_WINDOW_INDEX = "spans_project_gateway_started_idx"

PROJECT_EXPRESSION = (
    "project_id = (SELECT NULLIF(current_setting('app.project_id', true), '')::uuid)"
)
BYPASS_EXPRESSION = "(SELECT current_setting('app.bypass_rls', true)) = 'on'"
PREFIX_EXPRESSION = "prefix = (SELECT NULLIF(current_setting('app.gateway_key_prefix', true), ''))"


def _index_is_valid(name: str) -> bool | None:
    """True if the index exists and is valid, False if it exists but is INVALID, None if absent.

    As in 0016. Offline (`--sql`) there is no database to ask, so the answer is None.
    """
    context = op.get_context()
    if context.as_sql:
        return None
    row = context.bind.execute(  # type: ignore[union-attr]  # bind is set when not as_sql
        sa.text(
            "SELECT i.indisvalid FROM pg_index AS i JOIN pg_class AS c ON c.oid = i.indexrelid "
            "WHERE c.relname = :name AND c.relnamespace = current_schema()::regnamespace"
        ),
        {"name": name},
    ).first()
    return None if row is None else bool(row[0])


def _build_index(name: str, definition: str) -> None:
    """Create `name` concurrently unless a valid one exists; drop an INVALID leftover first."""
    state = _index_is_valid(name)
    if state is True:
        return
    if state is False:
        op.execute(f"DROP INDEX CONCURRENTLY IF EXISTS {name}")
    op.execute(f"CREATE INDEX CONCURRENTLY {name} {definition}")


def upgrade() -> None:
    with op.get_context().autocommit_block():
        # The ALTER needs a brief ACCESS EXCLUSIVE lock; waiting behind a long transaction for it
        # would stall every ingest queued behind the wait, so it fails fast instead (as in 0017).
        op.execute(f"SET lock_timeout = '{LOCK_TIMEOUT}'")
        op.execute("ALTER TABLE spans ADD COLUMN IF NOT EXISTS source_key_id uuid")
        op.execute("RESET lock_timeout")
        _build_index(
            SPANS_INDEX,
            "ON spans (project_id, source_key_id, started_at) WHERE source_key_id IS NOT NULL",
        )
        _build_index(
            SPANS_WINDOW_INDEX,
            "ON spans (project_id, started_at) WHERE source_key_id IS NOT NULL",
        )

    op.execute(
        """
        CREATE TABLE gateway_keys (
            id                 uuid PRIMARY KEY,
            project_id         uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            route_id           uuid,
            name               text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
            prefix             text NOT NULL,
            secret_hash        bytea NOT NULL,
            environment        text NOT NULL CHECK (char_length(environment) BETWEEN 1 AND 64),
            rpm_limit          integer CHECK (rpm_limit BETWEEN 1 AND 100000),
            tpm_limit          integer CHECK (tpm_limit BETWEEN 1 AND 100000000),
            allowed_models     text[] NOT NULL DEFAULT '{}'
                CHECK (cardinality(allowed_models) <= 100),
            default_tags       text[] NOT NULL DEFAULT '{}'
                CHECK (cardinality(default_tags) <= 20),
            cache_ttl_seconds  integer CHECK (cache_ttl_seconds BETWEEN 1 AND 86400),
            created_by         uuid REFERENCES users (id) ON DELETE SET NULL,
            created_at         timestamptz NOT NULL DEFAULT now(),
            last_used_at       timestamptz,
            revoked_at         timestamptz,
            CONSTRAINT gateway_keys_prefix_key UNIQUE (prefix),
            CONSTRAINT gateway_keys_id_project_key UNIQUE (id, project_id),
            CONSTRAINT gateway_keys_route_fkey FOREIGN KEY (route_id, project_id)
                REFERENCES gateway_routes (id, project_id) ON DELETE RESTRICT,
            CONSTRAINT gateway_keys_route_required
                CHECK (route_id IS NOT NULL OR revoked_at IS NOT NULL)
        )
        """
    )
    op.execute(
        "CREATE INDEX gateway_keys_project_created_idx ON gateway_keys (project_id, created_at)"
    )
    op.execute("CREATE INDEX gateway_keys_route_idx ON gateway_keys (route_id)")
    op.execute("CREATE INDEX gateway_keys_created_by_idx ON gateway_keys (created_by)")

    op.execute(
        """
        CREATE TABLE gateway_key_minutes (
            key_id        uuid NOT NULL,
            minute_start  timestamptz NOT NULL,
            project_id    uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            requests      integer NOT NULL DEFAULT 0 CHECK (requests >= 0),
            tokens        bigint NOT NULL DEFAULT 0 CHECK (tokens >= 0),
            PRIMARY KEY (key_id, minute_start),
            CONSTRAINT gateway_key_minutes_key_fkey FOREIGN KEY (key_id, project_id)
                REFERENCES gateway_keys (id, project_id) ON DELETE CASCADE
        )
        """
    )
    op.execute("CREATE INDEX gateway_key_minutes_project_idx ON gateway_key_minutes (project_id)")

    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_project_isolation ON {table} "
            f"USING ({PROJECT_EXPRESSION}) WITH CHECK ({PROJECT_EXPRESSION})"
        )
        op.execute(
            f"CREATE POLICY {table}_worker_bypass ON {table} "
            f"USING ({BYPASS_EXPRESSION}) WITH CHECK ({BYPASS_EXPRESSION})"
        )
    # Read-only: shows the one key whose prefix the gateway was presented (see the docstring).
    op.execute(
        "CREATE POLICY gateway_keys_prefix_lookup ON gateway_keys FOR SELECT "
        f"USING ({PREFIX_EXPRESSION})"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS gateway_key_minutes")
    op.execute("DROP TABLE IF EXISTS gateway_keys")
    with op.get_context().autocommit_block():
        op.execute(f"DROP INDEX CONCURRENTLY IF EXISTS {SPANS_WINDOW_INDEX}")
        op.execute(f"DROP INDEX CONCURRENTLY IF EXISTS {SPANS_INDEX}")
        op.execute(f"SET lock_timeout = '{LOCK_TIMEOUT}'")
        op.execute("ALTER TABLE spans DROP COLUMN IF EXISTS source_key_id")
        op.execute("RESET lock_timeout")
