"""Add fault profiles, and the profile a gateway key runs.

Revision ID: 0204
Revises: 0203
Create Date: 2026-10-09

A fault profile is a project's description of one failure to inject into gateway calls made with
the keys it is attached to (the Integration Lab): a `scenario` (a rate limit, a malformed body,
a dropped stream, ...), its `params`, and the `probability` that a call gets it. The params are
validated per scenario by `app.gateway.fault_params` before they are stored; the database only
requires a JSON object. A disabled or expired profile does nothing.

Choices worth knowing about:

* The ids are UUIDv7 generated by the application, so the column has no default. `project_id`
  cascades, so deleting a project deletes its profiles. `created_by` is `ON DELETE SET NULL`:
  removing a person keeps the profiles they wrote.
* `UNIQUE (project_id, name)` makes a name pick out one profile in its project (a duplicate is
  `409 FAULT_PROFILE_NAME_TAKEN`); its index leads with `project_id`, so it also serves the
  foreign key and the per-project list. `UNIQUE (id, project_id)` exists only to be the target
  of the composite key from `gateway_keys`.
* `scenario` is a PostgreSQL enum, one value per scenario the gateway can inject. Adding a
  scenario later is `ALTER TYPE ... ADD VALUE`, which is safe outside a transaction block.
* `probability` is `numeric(4, 3)` between 0 and 1 (three decimals, as the API takes it).
* `gateway_keys.fault_profile_id` references `fault_profiles (id, project_id)` through the key's
  own `project_id`, so a key can only run a profile of its own project: the database refuses a
  cross-project reference, not only the service. The key's `project_id` is `NOT NULL`, so the
  action is `ON DELETE SET NULL (fault_profile_id)`, which nulls the profile column and leaves
  `project_id` alone (PostgreSQL 15 and later). Deleting a profile detaches its keys. Because
  the reference is nullable and the default match type skips a constraint with a NULL column,
  a key without a profile is unconstrained.
* The index on `gateway_keys (fault_profile_id)` is partial (`WHERE fault_profile_id IS NOT
  NULL`): most keys run no profile, and the index only serves the lookup that deleting a profile
  and listing "which keys run this profile" make.
* The production rule (a profile never attaches to, or survives a move to, a `production` key)
  is enforced by the key service under the key's row lock: the key's `environment` is free text,
  so no CHECK can express it without freezing the vocabulary.
* Row-level security is the policy pair every project-scoped table has, in the InitPlan form of
  0017: a row is visible when it belongs to the project bound to the transaction, or when
  worker code opted into bypass.
* The ALTER of `gateway_keys` adds a nullable column without a default (catalog only) and one
  foreign key, which validates against a table that holds a handful of keys per project; the
  lock wait is capped at 5 seconds, so a long transaction on the table fails the migration
  instead of stalling the gateway queued behind it.

Downgrade drops the key's reference, then the table and the type. Fault profiles are gone with
them and no key runs one.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0204"
down_revision: str | None = "0203"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCENARIOS = (
    "auth_expired",
    "scope_denied",
    "rate_limited",
    "unsupported_parameter",
    "provider_5xx",
    "malformed_json",
    "truncated_stream",
    "slow_response",
    "timeout",
)
LOCK_TIMEOUT = "5s"

PROJECT_EXPRESSION = (
    "project_id = (SELECT NULLIF(current_setting('app.project_id', true), '')::uuid)"
)
BYPASS_EXPRESSION = "(SELECT current_setting('app.bypass_rls', true)) = 'on'"


def upgrade() -> None:
    values = ", ".join(f"'{scenario}'" for scenario in SCENARIOS)
    op.execute(f"CREATE TYPE fault_scenario AS ENUM ({values})")
    op.execute(
        """
        CREATE TABLE fault_profiles (
            id           uuid PRIMARY KEY,
            project_id   uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            name         text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
            scenario     fault_scenario NOT NULL,
            params       jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(params) = 'object'),
            probability  numeric(4, 3) NOT NULL DEFAULT 1
                CHECK (probability BETWEEN 0 AND 1),
            enabled      boolean NOT NULL DEFAULT true,
            expires_at   timestamptz,
            created_by   uuid REFERENCES users (id) ON DELETE SET NULL,
            created_at   timestamptz NOT NULL DEFAULT now(),
            updated_at   timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT fault_profiles_project_name_key UNIQUE (project_id, name),
            CONSTRAINT fault_profiles_id_project_key UNIQUE (id, project_id)
        )
        """
    )
    op.execute("CREATE INDEX fault_profiles_created_by_idx ON fault_profiles (created_by)")
    op.execute("ALTER TABLE fault_profiles ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE fault_profiles FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY fault_profiles_project_isolation ON fault_profiles "
        f"USING ({PROJECT_EXPRESSION}) WITH CHECK ({PROJECT_EXPRESSION})"
    )
    op.execute(
        "CREATE POLICY fault_profiles_worker_bypass ON fault_profiles "
        f"USING ({BYPASS_EXPRESSION}) WITH CHECK ({BYPASS_EXPRESSION})"
    )

    op.execute(f"SET LOCAL lock_timeout = '{LOCK_TIMEOUT}'")
    op.execute("ALTER TABLE gateway_keys ADD COLUMN fault_profile_id uuid")
    op.execute(
        "ALTER TABLE gateway_keys ADD CONSTRAINT gateway_keys_fault_profile_fkey "
        "FOREIGN KEY (fault_profile_id, project_id) REFERENCES fault_profiles (id, project_id) "
        "ON DELETE SET NULL (fault_profile_id)"
    )
    op.execute(
        "CREATE INDEX gateway_keys_fault_profile_idx ON gateway_keys (fault_profile_id) "
        "WHERE fault_profile_id IS NOT NULL"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS gateway_keys_fault_profile_idx")
    op.execute("ALTER TABLE gateway_keys DROP CONSTRAINT IF EXISTS gateway_keys_fault_profile_fkey")
    op.execute("ALTER TABLE gateway_keys DROP COLUMN IF EXISTS fault_profile_id")
    op.execute("DROP TABLE IF EXISTS fault_profiles")
    op.execute("DROP TYPE IF EXISTS fault_scenario")
