"""Add alert channels, and allow the Phase 3 audit actions.

Revision ID: 0301
Revises: 0300
Create Date: 2026-10-10

An alert channel is where an organization's alerts go: a list of email recipients, a Slack
incoming webhook, a signed HTTP webhook or a PagerDuty service. Rules in any of the
organization's projects name the channels they notify.

Choices worth knowing about:

* The ids are UUIDv7 generated by the application, like every other public id, so the column
  has no default.
* The table is scoped to an organization, not a project, so it has no row-level security: every
  query filters by `org_id` (`app.alerts.queries`). `org_id` cascades, so deleting an
  organization deletes its channels.
* `config` holds the kind's non-secret settings as a JSON object (`app.alerts.schemas`). The
  secret part of a channel (the Slack URL, the webhook signing secret, the PagerDuty routing
  key) is sealed in the application (`app.core.crypto`): `secret_enc` holds the sealed bytes and
  `secret_key_id` the id of the key that sealed them. The CHECK keeps the two together. An email
  channel has neither.
* `UNIQUE (org_id, name)` makes a name pick out one channel in its organization (a duplicate is
  `409 CHANNEL_NAME_TAKEN`). Its index leads with `org_id`, so it also serves the foreign key and
  the per-organization list; a separate `org_id` index would duplicate it.
* `created_by` is `ON DELETE SET NULL`: removing a person keeps the channels they added. It has
  its own index so that deleting a user does not scan the table.
* `verified_at` is when a test notification last went through; NULL until one does.

`audit_events.action` is a CHECK over a fixed list, so it is dropped and added again with every
Phase 3 action, as in 0200. The migration is one transaction; `audit_events` stays locked while
the new constraint scans its rows, which is acceptable for a table of small, infrequent rows.
The wait for that lock is capped at 5 seconds (`SET LOCAL lock_timeout`, as in 0017 and 0204), so
a long transaction on `audit_events` fails the migration instead of queueing every audited write
behind it. If it times out, run it again.

Downgrade deletes the audit events that use the new actions, which the older constraint would
reject, restores the previous list, and drops the table and its enum type. The sealed secrets
are gone with it.
"""

from collections.abc import Sequence

from alembic import op

PREVIOUS_AUDIT_ACTIONS = (
    "org.create",
    "member.add",
    "member.role_change",
    "member.remove",
    "invite.create",
    "invite.revoke",
    "invite.accept",
    "project.create",
    "project.update",
    "key.create",
    "key.revoke",
    "user.password_reset",
    "user.oauth_link",
    "user.oauth_unlink",
    "user.totp_enable",
    "user.totp_disable",
    "org.update",
    "project.delete",
    "credential.create",
    "credential.rotate",
    "credential.delete",
    "gateway_route.create",
    "gateway_route.update",
    "gateway_route.revert",
    "gateway_route.delete",
    "gateway_key.create",
    "gateway_key.update",
    "gateway_key.revoke",
    "fault_profile.create",
    "fault_profile.update",
    "fault_profile.delete",
    "price_override.create",
    "price_override.delete",
    "gateway_cache.purge",
)
NEW_AUDIT_ACTIONS = (
    "alert_channel.create",
    "alert_channel.update",
    "alert_channel.delete",
    "alert_channel.test",
    "alert_channel.retry_delivery",
    "alert_rule.create",
    "alert_rule.update",
    "alert_rule.delete",
    "alert_rule.mute",
    "alert_event.acknowledge",
    "budget.create",
    "budget.update",
    "budget.delete",
)

revision: str = "0301"
down_revision: str | None = "0300"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

LOCK_TIMEOUT = "5s"


def upgrade() -> None:
    op.execute(f"SET LOCAL lock_timeout = '{LOCK_TIMEOUT}'")
    op.execute("CREATE TYPE alert_channel_kind AS ENUM ('email', 'slack', 'webhook', 'pagerduty')")
    op.execute(
        """
        CREATE TABLE alert_channels (
            id            uuid PRIMARY KEY,
            org_id        uuid NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
            kind          alert_channel_kind NOT NULL,
            name          text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
            config        jsonb NOT NULL CHECK (jsonb_typeof(config) = 'object'),
            secret_enc    bytea,
            secret_key_id text,
            verified_at   timestamptz,
            created_by    uuid REFERENCES users (id) ON DELETE SET NULL,
            created_at    timestamptz NOT NULL DEFAULT now(),
            updated_at    timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT alert_channels_org_name_key UNIQUE (org_id, name),
            CONSTRAINT alert_channels_secret_pair CHECK (
                (secret_enc IS NULL) = (secret_key_id IS NULL)
            )
        )
        """
    )
    op.execute("CREATE INDEX alert_channels_created_by_idx ON alert_channels (created_by)")
    _set_audit_actions((*PREVIOUS_AUDIT_ACTIONS, *NEW_AUDIT_ACTIONS))


def downgrade() -> None:
    op.execute(f"SET LOCAL lock_timeout = '{LOCK_TIMEOUT}'")
    listed = ", ".join(f"'{action}'" for action in NEW_AUDIT_ACTIONS)
    op.execute(f"DELETE FROM audit_events WHERE action IN ({listed})")
    _set_audit_actions(PREVIOUS_AUDIT_ACTIONS)
    op.execute("DROP TABLE IF EXISTS alert_channels")
    op.execute("DROP TYPE IF EXISTS alert_channel_kind")


def _set_audit_actions(actions: tuple[str, ...]) -> None:
    listed = ", ".join(f"'{action}'" for action in actions)
    op.execute("ALTER TABLE audit_events DROP CONSTRAINT audit_events_action_check")
    op.execute(
        "ALTER TABLE audit_events ADD CONSTRAINT audit_events_action_check "
        f"CHECK (action IN ({listed}))"
    )
