"""Add alert rules, their current state and their event history.

Revision ID: 0303
Revises: 0302
Create Date: 2026-10-10

An alert rule watches one metric of a project over a trailing window and notifies the rule's
channels when it crosses a line. `alert_states` holds each rule's current state, one row the
evaluation job overwrites every pass; `alert_events` holds one row per firing episode, from the
moment it fired until it resolved.

Choices worth knowing about:

* The ids are UUIDv7 generated by the application, so the columns have no default. Every table
  carries `project_id` and cascades from `projects`, so deleting a project deletes its rules,
  states and events.
* `kind` is `threshold` (a fixed line), `anomaly` (a line drawn from the previous windows) or
  `budget` (the hidden rule a budget owns; its period replaces the window). The kind decides
  which columns are set, and the CHECKs hold that: `window_minutes` is NULL exactly for budget
  rules, `threshold` exactly for anomaly rules, and `baseline_windows` and `sensitivity` are set
  exactly for anomaly rules. `metric = 'spend'` exactly for budget rules. The bounds repeat the
  API's limits so a row the API would refuse cannot be written another way.
* `kind`, `metric`, `comparator` and the state are PostgreSQL enums, like the gateway's. Adding
  a value later is `ALTER TYPE ... ADD VALUE`.
* `filters` is a JSON object of exact-match filters (`environment`, `provider`, `model` for the
  rules people write; a budget's scope for budget rules). The API checks the keys.
* `channel_ids` is an array without foreign keys: channels belong to the organization, a channel
  can be deleted while rules still name it, and the evaluation job skips an id that no longer
  resolves. At most 10, by CHECK.
* `UNIQUE (id, project_id)` is the target of the composite keys from `alert_states` and
  `alert_events`, which repeat `project_id` so their row-level security policy is the same column
  test as every other project-scoped table, and the keys keep the two equal.
* `alert_events` allows one open event (`resolved_at IS NULL`) per rule, by a partial unique
  index: a second fire while one is open is a bug the database refuses. `state` is the state the
  event recorded when it was opened.
* `created_by` and `acknowledged_by` are `ON DELETE SET NULL`: removing a person keeps the rules
  they wrote and the events they acknowledged. An acknowledger implies an acknowledgement time
  (CHECK); the time stays when the person is deleted. Both columns have an index so deleting a
  user does not scan the tables; the acknowledger's is partial, since most events are never
  acknowledged.
* Row-level security on all three tables is the policy pair every project-scoped table has, in
  the InitPlan form of 0017.

The migration creates new tables only, in one transaction. Downgrade drops them and their types;
the rules and their history are gone with them.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0303"
down_revision: str | None = "0302"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = ("alert_rules", "alert_states", "alert_events")
TYPES = ("alert_rule_kind", "alert_metric", "alert_comparator", "alert_rule_state")

PROJECT_EXPRESSION = (
    "project_id = (SELECT NULLIF(current_setting('app.project_id', true), '')::uuid)"
)
BYPASS_EXPRESSION = "(SELECT current_setting('app.bypass_rls', true)) = 'on'"


def upgrade() -> None:
    op.execute("CREATE TYPE alert_rule_kind AS ENUM ('threshold', 'anomaly', 'budget')")
    op.execute(
        "CREATE TYPE alert_metric AS ENUM "
        "('error_rate', 'p95_ms', 'ttft_p95_ms', 'cost_usd', 'llm_calls', 'tokens', 'spend')"
    )
    op.execute("CREATE TYPE alert_comparator AS ENUM ('gt', 'gte', 'lt', 'lte')")
    op.execute("CREATE TYPE alert_rule_state AS ENUM ('ok', 'firing')")

    op.execute(
        """
        CREATE TABLE alert_rules (
            id                uuid PRIMARY KEY,
            project_id        uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            name              text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
            kind              alert_rule_kind NOT NULL,
            metric            alert_metric NOT NULL,
            filters           jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(filters) = 'object'),
            window_minutes    integer CHECK (window_minutes BETWEEN 5 AND 1440),
            comparator        alert_comparator NOT NULL,
            threshold         numeric CHECK (threshold >= 0),
            baseline_windows  integer CHECK (baseline_windows BETWEEN 3 AND 30),
            sensitivity       numeric CHECK (sensitivity BETWEEN 0.5 AND 5.0),
            cooldown_minutes  integer NOT NULL DEFAULT 15
                CHECK (cooldown_minutes BETWEEN 0 AND 1440),
            enabled           boolean NOT NULL DEFAULT true,
            channel_ids       uuid[] NOT NULL DEFAULT '{}' CHECK (cardinality(channel_ids) <= 10),
            muted_until       timestamptz,
            created_by        uuid REFERENCES users (id) ON DELETE SET NULL,
            created_at        timestamptz NOT NULL DEFAULT now(),
            updated_at        timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT alert_rules_id_project_key UNIQUE (id, project_id),
            CONSTRAINT alert_rules_window_for_kind
                CHECK ((window_minutes IS NULL) = (kind = 'budget')),
            CONSTRAINT alert_rules_threshold_for_kind
                CHECK ((threshold IS NULL) = (kind = 'anomaly')),
            CONSTRAINT alert_rules_baseline_for_kind
                CHECK ((baseline_windows IS NOT NULL) = (kind = 'anomaly')),
            CONSTRAINT alert_rules_sensitivity_for_kind
                CHECK ((sensitivity IS NOT NULL) = (kind = 'anomaly')),
            CONSTRAINT alert_rules_spend_for_kind
                CHECK ((metric = 'spend') = (kind = 'budget'))
        )
        """
    )
    op.execute("CREATE INDEX alert_rules_project_idx ON alert_rules (project_id)")
    op.execute("CREATE INDEX alert_rules_created_by_idx ON alert_rules (created_by)")

    op.execute(
        """
        CREATE TABLE alert_states (
            rule_id            uuid PRIMARY KEY,
            project_id         uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            state              alert_rule_state NOT NULL,
            since              timestamptz,
            last_value         numeric,
            last_evaluated_at  timestamptz,
            CONSTRAINT alert_states_rule_fkey FOREIGN KEY (rule_id, project_id)
                REFERENCES alert_rules (id, project_id) ON DELETE CASCADE
        )
        """
    )
    op.execute("CREATE INDEX alert_states_project_idx ON alert_states (project_id)")

    op.execute(
        """
        CREATE TABLE alert_events (
            id               uuid PRIMARY KEY,
            project_id       uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            rule_id          uuid NOT NULL,
            state            alert_rule_state NOT NULL,
            value            numeric,
            threshold        numeric,
            started_at       timestamptz NOT NULL,
            resolved_at      timestamptz,
            acknowledged_by  uuid REFERENCES users (id) ON DELETE SET NULL,
            acknowledged_at  timestamptz,
            payload          jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(payload) = 'object'),
            CONSTRAINT alert_events_rule_fkey FOREIGN KEY (rule_id, project_id)
                REFERENCES alert_rules (id, project_id) ON DELETE CASCADE,
            CONSTRAINT alert_events_resolved_after_start
                CHECK (resolved_at IS NULL OR resolved_at >= started_at),
            CONSTRAINT alert_events_acknowledged_pair
                CHECK (acknowledged_by IS NULL OR acknowledged_at IS NOT NULL)
        )
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX alert_events_one_open_per_rule_key ON alert_events (rule_id) "
        "WHERE resolved_at IS NULL"
    )
    op.execute(
        "CREATE INDEX alert_events_project_started_idx "
        "ON alert_events (project_id, started_at DESC, id DESC)"
    )
    op.execute(
        "CREATE INDEX alert_events_rule_started_idx "
        "ON alert_events (rule_id, started_at DESC, id DESC)"
    )
    op.execute(
        "CREATE INDEX alert_events_acknowledged_by_idx ON alert_events (acknowledged_by) "
        "WHERE acknowledged_by IS NOT NULL"
    )

    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_project_isolation ON {table} "
            f"USING ({PROJECT_EXPRESSION}) WITH CHECK ({PROJECT_EXPRESSION})"
        )
        op.execute(
            f"CREATE POLICY {table}_worker_bypass ON {table} "
            f"USING ({BYPASS_EXPRESSION}) WITH CHECK ({BYPASS_EXPRESSION})"
        )


def downgrade() -> None:
    for table in reversed(TABLES):
        op.execute(f"DROP TABLE IF EXISTS {table}")
    for type_name in reversed(TYPES):
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
