"""Add budgets: a spend cap per project, gateway key, end user or model.

Revision ID: 0304
Revises: 0303
Create Date: 2026-10-10

A budget caps the spend of one scope over a UTC day or month. It is evaluated by a hidden alert
rule it owns (`alert_rules.kind = 'budget'`): the rule reads `spend` over the budget's period and
fires when it passes `amount_usd`. A `block` budget whose rule is firing makes the gateway refuse
calls in its scope.

Choices worth knowing about:

* The id is a UUIDv7 generated by the application, so the column has no default. The table
  carries `project_id` and cascades from `projects`.
* `scope` names whose spend counts: the whole project, one gateway key, one end user (the trace's
  `external_user_id`) or one model. `scope_id` holds that key id, user or model as text, and is
  NULL exactly for a `project` budget (CHECK). There is no foreign key to the gateway key: the API
  checks it belongs to the project when the budget is saved, and a deleted key leaves a budget
  that matches nothing.
* `scope`, `period` and `action` are PostgreSQL enums, like the alert rules'.
* `amount_usd` is `numeric(14,4)` and strictly positive.
* `channel_ids` mirrors the rule's: channels of the organization, without foreign keys, at most
  10.
* `rule_id` is the budget's rule, one budget per rule (UNIQUE). The composite key
  `(rule_id, project_id)` targets `alert_rules (id, project_id)`, so the two share a project, and
  cascades: deleting the rule deletes the budget. The API deletes both together.
* `created_by` is `ON DELETE SET NULL` and indexed, so deleting a user does not scan the table.
* Indexes: `(project_id)` for the budgets page and `(project_id, scope, scope_id)` for the
  gateway's lookup of the budgets that apply to a call. `UNIQUE (project_id, name)` keeps names
  apart within a project.
* Row-level security is the policy pair every project-scoped table has, in the InitPlan form of
  0017.

The migration creates a new table only, in one transaction. Downgrade drops it and its types.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0304"
down_revision: str | None = "0303"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TYPES = ("budget_scope", "budget_period", "budget_action")

PROJECT_EXPRESSION = (
    "project_id = (SELECT NULLIF(current_setting('app.project_id', true), '')::uuid)"
)
BYPASS_EXPRESSION = "(SELECT current_setting('app.bypass_rls', true)) = 'on'"


def upgrade() -> None:
    op.execute("CREATE TYPE budget_scope AS ENUM ('project', 'gateway_key', 'user', 'model')")
    op.execute("CREATE TYPE budget_period AS ENUM ('daily', 'monthly')")
    op.execute("CREATE TYPE budget_action AS ENUM ('notify', 'block')")
    _create_table()
    _enable_rls()


def _create_table() -> None:
    op.execute(
        """
        CREATE TABLE budgets (
            id           uuid PRIMARY KEY,
            project_id   uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            name         text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
            scope        budget_scope NOT NULL,
            scope_id     text CHECK (char_length(scope_id) BETWEEN 1 AND 200),
            period       budget_period NOT NULL,
            amount_usd   numeric(14, 4) NOT NULL CHECK (amount_usd > 0),
            action       budget_action NOT NULL,
            enabled      boolean NOT NULL DEFAULT true,
            channel_ids  uuid[] NOT NULL DEFAULT '{}' CHECK (cardinality(channel_ids) <= 10),
            rule_id      uuid NOT NULL,
            created_by   uuid REFERENCES users (id) ON DELETE SET NULL,
            created_at   timestamptz NOT NULL DEFAULT now(),
            updated_at   timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT budgets_project_name_key UNIQUE (project_id, name),
            CONSTRAINT budgets_rule_key UNIQUE (rule_id),
            CONSTRAINT budgets_rule_fkey FOREIGN KEY (rule_id, project_id)
                REFERENCES alert_rules (id, project_id) ON DELETE CASCADE,
            CONSTRAINT budgets_scope_id_for_scope
                CHECK ((scope_id IS NULL) = (scope = 'project'))
        )
        """
    )
    op.execute("CREATE INDEX budgets_project_idx ON budgets (project_id)")
    op.execute("CREATE INDEX budgets_project_scope_idx ON budgets (project_id, scope, scope_id)")
    op.execute("CREATE INDEX budgets_created_by_idx ON budgets (created_by)")


def _enable_rls() -> None:
    op.execute("ALTER TABLE budgets ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE budgets FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY budgets_project_isolation ON budgets "
        f"USING ({PROJECT_EXPRESSION}) WITH CHECK ({PROJECT_EXPRESSION})"
    )
    op.execute(
        "CREATE POLICY budgets_worker_bypass ON budgets "
        f"USING ({BYPASS_EXPRESSION}) WITH CHECK ({BYPASS_EXPRESSION})"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS budgets")
    for type_name in reversed(TYPES):
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
