"""Add insights, detector runs and the project's insight channels, and allow the insight audit
actions.

Revision ID: 0402
Revises: 0401
Create Date: 2026-10-10

An insight is a problem the detectors found in a project's spans, with its cause and a fix. One
row per problem: a fingerprint (`app.insights.fingerprint`) names it, and every later detection
of the same problem updates that row (`app.insights.service.apply_findings`). `detector_runs`
records each detector's pass over a project, so a quiet page can be told apart from a detector
that failed or never ran.

Choices worth knowing about:

* The ids are UUIDv7 generated by the application, so the columns have no default. Both tables
  carry `project_id` and cascade from `projects`, so deleting a project deletes its insights
  and runs.
* `severity` and `status` are PostgreSQL enums, like the alert enums. Adding a value later is
  `ALTER TYPE ... ADD VALUE`.
* The copy (title, summary, suggested fix, verification, failure layer, certainty) is stored
  with the row, so an insight reads the same after the catalogue's wording changes. The layer
  and certainty CHECKs repeat the catalogue's vocabularies.
* `UNIQUE (project_id, fingerprint)` is the conflict target of the upsert that applies a batch
  of findings. Its index leads with `project_id`, so it also serves the foreign key.
* The status decides which columns are set, and the CHECKs hold that: `resolved_at` exactly
  when resolved, `muted_until` exactly when muted, a mute reason exactly with a mute end, an
  acknowledgement whenever the status is `acknowledged` and never while it is `open` (a reopened
  insight starts unacknowledged). `acknowledged_by` is `ON DELETE SET NULL`: removing a person
  keeps the acknowledgement time. Its index is partial, since most insights are never
  acknowledged, and keeps deleting a user from scanning the table.
* `(project_id, status, last_seen_at DESC, id DESC)` serves the list's keyset order, the status
  filter and the auto-resolve pass. The GIN index on `evidence -> 'trace_ids'` (`jsonb_path_ops`)
  answers "which insights cite this trace" for the trace page.
* `detector_runs.findings` is NULL exactly when the run failed (`error` is set): a detector that
  raised found an unknown number of problems, not zero. `(project_id, ran_at DESC)` serves the
  runs list and the stale-first project order of the detector job.
* `projects.insight_channel_ids` names the alert channels that hear about critical insights. It
  is an array without foreign keys, like `alert_rules.channel_ids`: channels belong to the
  organization, a channel can be deleted while a project still names it, and notifying skips an
  id that no longer resolves. At most 10, by CHECK. The constant default is stored in the
  catalogue, so adding the column rewrites no rows.
* Row-level security on both new tables is the policy pair every project-scoped table has, in
  the InitPlan form of 0017.

`audit_events.action` is a CHECK over a fixed list, so it is dropped and added again with every
action allowed so far plus the insight actions, as in 0301. `projects` and `audit_events` are
locked briefly; the wait for each lock is capped at 5 seconds (`SET LOCAL lock_timeout`, as in
0301 and 0305), so a long transaction fails the migration instead of queueing every request
behind it. If it times out, run it again.

Downgrade deletes the audit events that use the insight actions, which the older constraint
would reject, restores the previous list, drops the column, the tables and their types. The
insights and their history are gone with them.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0402"
down_revision: str | None = "0401"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

LOCK_TIMEOUT = "5s"

TABLES = ("insights", "detector_runs")
TYPES = ("insight_severity", "insight_status")

PROJECT_EXPRESSION = (
    "project_id = (SELECT NULLIF(current_setting('app.project_id', true), '')::uuid)"
)
BYPASS_EXPRESSION = "(SELECT current_setting('app.bypass_rls', true)) = 'on'"

# Every action 0301 allows, in its order.
PREVIOUS_AUDIT_ACTIONS = (
    "org.create",
    "member.add",
    "member.role_change",
    "member.remove",
    "invite.create",
    "invite.revoke",
    "invite.accept",
    "project.create",
    "project.update",
    "key.create",
    "key.revoke",
    "user.password_reset",
    "user.oauth_link",
    "user.oauth_unlink",
    "user.totp_enable",
    "user.totp_disable",
    "org.update",
    "project.delete",
    "credential.create",
    "credential.rotate",
    "credential.delete",
    "gateway_route.create",
    "gateway_route.update",
    "gateway_route.revert",
    "gateway_route.delete",
    "gateway_key.create",
    "gateway_key.update",
    "gateway_key.revoke",
    "fault_profile.create",
    "fault_profile.update",
    "fault_profile.delete",
    "price_override.create",
    "price_override.delete",
    "gateway_cache.purge",
    "alert_channel.create",
    "alert_channel.update",
    "alert_channel.delete",
    "alert_channel.test",
    "alert_channel.retry_delivery",
    "alert_rule.create",
    "alert_rule.update",
    "alert_rule.delete",
    "alert_rule.mute",
    "alert_event.acknowledge",
    "budget.create",
    "budget.update",
    "budget.delete",
)
NEW_AUDIT_ACTIONS = (
    "insight.acknowledge",
    "insight.resolve",
    "insight.mute",
    "insight.unmute",
    "insight.explain",
)


def upgrade() -> None:
    op.execute(f"SET LOCAL lock_timeout = '{LOCK_TIMEOUT}'")
    op.execute("CREATE TYPE insight_severity AS ENUM ('info', 'warning', 'critical')")
    op.execute("CREATE TYPE insight_status AS ENUM ('open', 'acknowledged', 'resolved', 'muted')")
    _create_insights()
    _create_detector_runs()
    for table in TABLES:
        _enable_row_level_security(table)
    op.execute(
        "ALTER TABLE projects ADD COLUMN insight_channel_ids uuid[] NOT NULL DEFAULT '{}' "
        "CONSTRAINT projects_insight_channel_ids_limit "
        "CHECK (cardinality(insight_channel_ids) <= 10)"
    )
    _set_audit_actions((*PREVIOUS_AUDIT_ACTIONS, *NEW_AUDIT_ACTIONS))


def downgrade() -> None:
    op.execute(f"SET LOCAL lock_timeout = '{LOCK_TIMEOUT}'")
    listed = ", ".join(f"'{action}'" for action in NEW_AUDIT_ACTIONS)
    op.execute(f"DELETE FROM audit_events WHERE action IN ({listed})")
    _set_audit_actions(PREVIOUS_AUDIT_ACTIONS)
    op.execute("ALTER TABLE projects DROP COLUMN IF EXISTS insight_channel_ids")
    for table in reversed(TABLES):
        op.execute(f"DROP TABLE IF EXISTS {table}")
    for type_name in reversed(TYPES):
        op.execute(f"DROP TYPE IF EXISTS {type_name}")


def _create_insights() -> None:
    op.execute(
        """
        CREATE TABLE insights (
            id               uuid PRIMARY KEY,
            project_id       uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            kind             text NOT NULL CHECK (char_length(kind) BETWEEN 1 AND 64),
            severity         insight_severity NOT NULL,
            status           insight_status NOT NULL,
            fingerprint      text NOT NULL CHECK (fingerprint ~ '^[0-9a-f]{32}$'),
            title            text NOT NULL,
            summary          text NOT NULL,
            failure_layer    text NOT NULL CHECK (failure_layer IN
                ('client', 'request', 'agent', 'provider', 'platform', 'traffic')),
            certainty        text NOT NULL CHECK (certainty IN ('measured', 'inferred')),
            evidence         jsonb NOT NULL CHECK (jsonb_typeof(evidence) = 'object'),
            suggested_fix    text NOT NULL,
            verification     text NOT NULL,
            first_seen_at    timestamptz NOT NULL,
            last_seen_at     timestamptz NOT NULL,
            occurrences      integer NOT NULL CHECK (occurrences >= 1),
            resolved_at      timestamptz,
            muted_until      timestamptz,
            mute_reason      text CHECK (char_length(mute_reason) BETWEEN 1 AND 500),
            acknowledged_by  uuid REFERENCES users (id) ON DELETE SET NULL,
            acknowledged_at  timestamptz,
            CONSTRAINT insights_project_fingerprint_key UNIQUE (project_id, fingerprint),
            CONSTRAINT insights_seen_order CHECK (last_seen_at >= first_seen_at),
            CONSTRAINT insights_resolved_for_status
                CHECK ((status = 'resolved') = (resolved_at IS NOT NULL)),
            CONSTRAINT insights_muted_for_status
                CHECK ((status = 'muted') = (muted_until IS NOT NULL)),
            CONSTRAINT insights_mute_pair
                CHECK ((muted_until IS NULL) = (mute_reason IS NULL)),
            CONSTRAINT insights_acknowledged_pair
                CHECK (acknowledged_by IS NULL OR acknowledged_at IS NOT NULL),
            CONSTRAINT insights_acknowledged_for_status
                CHECK (status <> 'acknowledged' OR acknowledged_at IS NOT NULL),
            CONSTRAINT insights_open_unacknowledged
                CHECK (status <> 'open' OR acknowledged_at IS NULL)
        )
        """
    )
    op.execute(
        "CREATE INDEX insights_project_status_seen_idx "
        "ON insights (project_id, status, last_seen_at DESC, id DESC)"
    )
    op.execute(
        "CREATE INDEX insights_evidence_trace_ids_idx "
        "ON insights USING gin ((evidence -> 'trace_ids') jsonb_path_ops)"
    )
    op.execute(
        "CREATE INDEX insights_acknowledged_by_idx ON insights (acknowledged_by) "
        "WHERE acknowledged_by IS NOT NULL"
    )


def _create_detector_runs() -> None:
    op.execute(
        """
        CREATE TABLE detector_runs (
            id            uuid PRIMARY KEY,
            project_id    uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            detector      text NOT NULL CHECK (char_length(detector) BETWEEN 1 AND 64),
            window_start  timestamptz NOT NULL,
            window_end    timestamptz NOT NULL,
            findings      integer CHECK (findings >= 0),
            truncated     boolean NOT NULL DEFAULT false,
            duration_ms   integer NOT NULL CHECK (duration_ms >= 0),
            error         text CHECK (char_length(error) BETWEEN 1 AND 500),
            ran_at        timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT detector_runs_window_order CHECK (window_end >= window_start),
            CONSTRAINT detector_runs_outcome CHECK ((findings IS NULL) = (error IS NOT NULL))
        )
        """
    )
    op.execute(
        "CREATE INDEX detector_runs_project_ran_idx ON detector_runs (project_id, ran_at DESC)"
    )


def _enable_row_level_security(table: str) -> None:
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY {table}_project_isolation ON {table} "
        f"USING ({PROJECT_EXPRESSION}) WITH CHECK ({PROJECT_EXPRESSION})"
    )
    op.execute(
        f"CREATE POLICY {table}_worker_bypass ON {table} "
        f"USING ({BYPASS_EXPRESSION}) WITH CHECK ({BYPASS_EXPRESSION})"
    )


def _set_audit_actions(actions: tuple[str, ...]) -> None:
    listed = ", ".join(f"'{action}'" for action in actions)
    op.execute("ALTER TABLE audit_events DROP CONSTRAINT audit_events_action_check")
    op.execute(
        "ALTER TABLE audit_events ADD CONSTRAINT audit_events_action_check "
        f"CHECK (action IN ({listed}))"
    )
