"""Add insight explanations.

Revision ID: 0403
Revises: 0402
Create Date: 2026-10-10

An explanation is Claude's account of one insight, asked for by an owner or admin. The table
also holds the explain budget's reservations: a row is inserted with `text` and `completed_at`
NULL and the call's worst-case cost before the provider is called. It is then completed: with the
answer and the real cost; with `text` NULL when the provider was (or may have been) paid but gave
no answer, so the spend stays counted; or deleted when the call failed without being billed. The
month-to-date sum over an organization's rows (reservations included) is what the
per-organization budget is checked against.

Choices worth knowing about:

* The id is UUIDv7 generated by the application, so the column has no default. `project_id`
  cascades from `projects`, and `(insight_id, project_id)` references `insights (id, project_id)`
  with `ON DELETE CASCADE`, so an explanation always belongs to an insight of its own project.
  That composite key needs `UNIQUE (id, project_id)` on `insights`, which this migration adds
  (the table is new in 0402, so building its index is quick). The wait for the lock on
  `insights` is capped at 5 seconds (`SET LOCAL lock_timeout`, as in 0402).
* A row with `text` is completed (CHECK). `completed_at` NULL marks a reservation; a completed
  row without `text` is a paid call without an answer, kept for the budget and never shown.
  `cost_usd` is never NULL: a reservation holds its worst case.
* `created_by` is `ON DELETE SET NULL`: removing a person keeps the explanations they asked for.
  Its index is partial, like the other `*_by` columns, so deleting a user does not scan the
  table.
* `(insight_id, created_at DESC)` serves the insight page's list; `(project_id, created_at)`
  serves the organization's month-to-date sum (one range per project) and the cleanup of stale
  reservations.
* Row-level security is the policy pair every project-scoped table has, in the InitPlan form of
  0017.

The migration creates one table and one constraint, in one transaction. Downgrade drops both;
the explanations are gone with them.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0403"
down_revision: str | None = "0402"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE = "insight_explanations"
LOCK_TIMEOUT = "5s"

PROJECT_EXPRESSION = (
    "project_id = (SELECT NULLIF(current_setting('app.project_id', true), '')::uuid)"
)
BYPASS_EXPRESSION = "(SELECT current_setting('app.bypass_rls', true)) = 'on'"


def upgrade() -> None:
    op.execute(f"SET LOCAL lock_timeout = '{LOCK_TIMEOUT}'")
    op.execute(
        "ALTER TABLE insights ADD CONSTRAINT insights_id_project_key UNIQUE (id, project_id)"
    )
    op.execute(
        """
        CREATE TABLE insight_explanations (
            id            uuid PRIMARY KEY,
            project_id    uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
            insight_id    uuid NOT NULL,
            model         text NOT NULL CHECK (char_length(model) BETWEEN 1 AND 128),
            text          text CHECK (char_length(text) <= 20000),
            cost_usd      numeric(14, 8) NOT NULL CHECK (cost_usd >= 0),
            created_by    uuid REFERENCES users (id) ON DELETE SET NULL,
            created_at    timestamptz NOT NULL DEFAULT now(),
            completed_at  timestamptz,
            CONSTRAINT insight_explanations_insight_fkey FOREIGN KEY (insight_id, project_id)
                REFERENCES insights (id, project_id) ON DELETE CASCADE,
            CONSTRAINT insight_explanations_text_when_completed
                CHECK (text IS NULL OR completed_at IS NOT NULL),
            CONSTRAINT insight_explanations_completed_after_created
                CHECK (completed_at IS NULL OR completed_at >= created_at)
        )
        """
    )
    op.execute(
        "CREATE INDEX insight_explanations_insight_created_idx "
        "ON insight_explanations (insight_id, created_at DESC)"
    )
    op.execute(
        "CREATE INDEX insight_explanations_project_created_idx "
        "ON insight_explanations (project_id, created_at)"
    )
    op.execute(
        "CREATE INDEX insight_explanations_created_by_idx ON insight_explanations (created_by) "
        "WHERE created_by IS NOT NULL"
    )

    op.execute(f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {TABLE} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY {TABLE}_project_isolation ON {TABLE} "
        f"USING ({PROJECT_EXPRESSION}) WITH CHECK ({PROJECT_EXPRESSION})"
    )
    op.execute(
        f"CREATE POLICY {TABLE}_worker_bypass ON {TABLE} "
        f"USING ({BYPASS_EXPRESSION}) WITH CHECK ({BYPASS_EXPRESSION})"
    )


def downgrade() -> None:
    op.execute(f"SET LOCAL lock_timeout = '{LOCK_TIMEOUT}'")
    op.execute(f"DROP TABLE IF EXISTS {TABLE}")
    op.execute("ALTER TABLE insights DROP CONSTRAINT IF EXISTS insights_id_project_key")
