"""Seed a Spanlight database for the load tests.

Creates an organization, an owner, a project, one ingest key (`ingest:write`) and ten read keys
(`traces:read`), then stores spans through the real ingestion pipeline, in this process, in
batches of 1 000. Calling `app.ingest.pipeline.ingest_spans` (validate, normalize, price, upsert)
means the rows are exactly what the API would have stored, laid out in time order (batches go
oldest first, see `seed_data.py`). It skips HTTP on purpose: the ingest limit of 50 requests a
second per key would turn 10 million spans into hours of waiting, and the load test would then
measure the seeder instead of the server.

It prints its rate every million spans and stops early when the seed is projected to take longer
than --max-minutes. Afterwards it builds the hourly rollups, runs VACUUM ANALYZE and prints the
table sizes and the free disk. The credentials are written to a JSON file only the current user can
read and are never printed.

    cd backend
    export LOAD_DATABASE_URL=postgresql+psycopg://postgres:...@127.0.0.1:55433/spanlight
    uv run python load/seed.py --spans 100000 --credentials-file ../.local/load/credentials.json

Connect as the database owner (the `postgres` user of the Compose stack). This is a test harness,
not a product path, so it does not go through the row-level security of the application role.

The data is generated by `seed_data.py` and the workspace created by `seed_workspace.py`, which
sit beside this file (running it as a script puts this directory on the import path).
"""

import argparse
import asyncio
import json
import math
import os
import sys
import time
import uuid
from collections.abc import Iterator
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, async_sessionmaker

from app.db.session import create_engine, create_session_factory
from app.ingest.pipeline import IngestTarget, ingest_spans
from app.ingest.schemas import MAX_SPANS_PER_BATCH
from app.rollups.compute import backfill_rollups
from seed_data import SPREAD, build_batch
from seed_workspace import Workspace, WorkspaceError, create_workspace

SPANS_PER_BATCH = MAX_SPANS_PER_BATCH  # the largest batch the API itself accepts
WORKERS = 4  # batches in flight: the database stays busy while one is being built
PROGRESS_EVERY = 1_000_000

TABLE_SIZES = text(
    """
    SELECT c.relname AS name, pg_size_pretty(pg_total_relation_size(c.oid)) AS total_size
    FROM pg_class AS c
    JOIN pg_namespace AS n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind = 'r'
      AND c.relname IN ('traces', 'spans', 'span_rollups_hourly', 'trace_rollups_hourly')
    ORDER BY pg_total_relation_size(c.oid) DESC
    """
)
COUNTS = text(
    """
    SELECT (SELECT count(*) FROM traces WHERE project_id = :project_id) AS traces,
           (SELECT count(*) FROM spans WHERE project_id = :project_id) AS spans
    """
)


class SeedError(Exception):
    """The seeding cannot continue; the message is printed and the exit status is 1."""


@dataclass(frozen=True)
class Options:
    spans: int
    credentials_file: Path
    seed: int
    max_minutes: float

    @property
    def batch_count(self) -> int:
        return math.ceil(self.spans / SPANS_PER_BATCH)


def say(message: str) -> None:
    print(f"seed: {message}", flush=True)


def write_credentials(path: Path, workspace: Workspace, data_end: datetime) -> None:
    """Write the credentials where only the current user can read them.

    `data_end` is the instant the seeded data ends at. The k6 scripts ask for time windows that end
    there and not at the wall clock, so a seed that takes hours does not leave the newest windows
    (the last hour, the end of the last day) empty by the time the scenarios start.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.unlink(missing_ok=True)  # the mode below only applies to a file that is created
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        json.dump(
            {
                "project_id": str(workspace.project_id),
                "ingest_key": workspace.ingest_key,
                "read_keys": workspace.read_keys,
                # Whole seconds with a Z, which every JavaScript Date parses and a URL can carry.
                "data_end": data_end.strftime("%Y-%m-%dT%H:%M:%SZ"),
            },
            handle,
        )


# ---------- ingestion ----------


@dataclass
class Progress:
    total: int
    started: float
    max_minutes: float
    done: int = 0
    next_report: int = PROGRESS_EVERY

    def add(self, accepted: int) -> None:
        """Count stored spans. Every `PROGRESS_EVERY` spans, print the rate and the time left, and
        stop if the whole seed is projected to take longer than the time budget.

        The projection uses the rate so far. Tables get slower as they grow, so it errs on the
        low side: a run it rejects was too slow, and one it accepts can still overrun.
        """
        self.done += accepted
        if self.done < self.next_report:
            return
        self.next_report += PROGRESS_EVERY
        minutes = (time.monotonic() - self.started) / 60
        rate = self.done / (minutes * 60)
        projected = self.total / rate / 60
        say(
            f"{self.done:,} of {self.total:,} spans stored ({minutes:.1f} min, {rate:,.0f} "
            f"spans/s, about {max(projected - minutes, 0):.0f} min left)"
        )
        if projected > self.max_minutes:
            raise SeedError(
                f"at {rate:,.0f} spans/s the {self.total:,} spans take about {projected:.0f} min, "
                f"more than the {self.max_minutes:g} min budget; store fewer spans or raise "
                "--max-minutes"
            )


def _batches(total: int) -> Iterator[tuple[int, int]]:
    """(batch index, span count) for every batch; the last one holds the remainder."""
    for index in range(math.ceil(total / SPANS_PER_BATCH)):
        yield index, min(SPANS_PER_BATCH, total - index * SPANS_PER_BATCH)


async def _worker(
    session_factory: async_sessionmaker[AsyncSession],
    target: IngestTarget,
    batches: Iterator[tuple[int, int]],
    options: Options,
    now: datetime,
    progress: Progress,
) -> None:
    # The workers share one iterator. `next` never awaits, so no two workers get the same batch.
    for index, count in batches:
        raw = build_batch(options.seed, index, count, now, options.batch_count)
        async with session_factory() as session:
            outcome = await ingest_spans(session, target, raw, now=now)
            if outcome.rejected or outcome.accepted != count:
                first = outcome.rejected[0].reason if outcome.rejected else "none reported"
                raise SeedError(f"batch {index}: {outcome.accepted} of {count} accepted ({first})")
            await session.commit()
        progress.add(outcome.accepted)


async def store_spans(
    session_factory: async_sessionmaker[AsyncSession],
    project_id: uuid.UUID,
    options: Options,
    now: datetime,
) -> None:
    target = IngestTarget(project_id=project_id, capture_payloads=True)
    progress = Progress(
        total=options.spans, started=time.monotonic(), max_minutes=options.max_minutes
    )
    batches = _batches(options.spans)
    # A TaskGroup cancels the other workers as soon as one fails.
    async with asyncio.TaskGroup() as group:
        for _ in range(WORKERS):
            group.create_task(_worker(session_factory, target, batches, options, now, progress))


# ---------- after seeding ----------


async def build_rollups(
    session_factory: async_sessionmaker[AsyncSession], project_id: uuid.UUID, now: datetime
) -> None:
    async with session_factory() as session:
        rows = await backfill_rollups(session, project_id, now - SPREAD - timedelta(hours=1), now)
    if rows == 0:
        # The overview for 7 and 30 days reads only the rollups, so without rows it would be
        # empty and fast, and the run would measure nothing.
        raise SeedError("the rollup backfill wrote no rows")
    say(f"rollups built: {rows:,} rows")


async def vacuum_analyze(engine: AsyncEngine) -> None:
    # VACUUM cannot run inside a transaction.
    async with engine.connect() as connection:
        autocommit = await connection.execution_options(isolation_level="AUTOCOMMIT")
        await autocommit.execute(text("VACUUM (ANALYZE)"))


async def verify_and_report(engine: AsyncEngine, project_id: uuid.UUID, expected: int) -> None:
    async with engine.connect() as connection:
        counts = (await connection.execute(COUNTS, {"project_id": project_id})).one()
        sizes = (await connection.execute(TABLE_SIZES)).all()
    if counts.spans != expected:
        raise SeedError(f"{counts.spans:,} spans were stored, expected {expected:,}")
    say(f"{counts.spans:,} spans in {counts.traces:,} traces")
    for row in sizes:
        say(f"table {row.name}: {row.total_size}")
    say("disk:")
    # A fixed command with no input, run only to show the free disk in the log.
    df = await asyncio.create_subprocess_exec("df", "-h")
    await df.wait()


# ---------- entry point ----------


def parse_options(argv: list[str]) -> Options:
    parser = argparse.ArgumentParser(description="Seed a database for the Spanlight load tests.")
    parser.add_argument("--spans", type=int, default=100_000, help="spans to store")
    parser.add_argument(
        "--credentials-file", type=Path, required=True, help="where to write the keys (JSON)"
    )
    parser.add_argument("--seed", type=int, default=1, help="same seed, same data shape")
    parser.add_argument(
        "--max-minutes",
        type=float,
        default=240.0,
        help="stop early when storing the spans is projected to take longer (default: 240, the "
        "share of the 330 minute `full` job left once the build, the rollups and the scenarios "
        "are counted)",
    )
    args = parser.parse_args(argv)
    if args.spans < 1:
        parser.error("--spans must be at least 1")
    if args.max_minutes <= 0:
        parser.error("--max-minutes must be positive")
    return Options(
        spans=args.spans,
        credentials_file=args.credentials_file,
        seed=args.seed,
        max_minutes=args.max_minutes,
    )


async def run(options: Options, database_url: str) -> None:
    engine = create_engine(database_url, pool_size=WORKERS + 1)
    session_factory = create_session_factory(engine)
    now = datetime.now(UTC)
    try:
        workspace = await create_workspace(session_factory)
        say(f"project {workspace.project_id} created; storing {options.spans:,} spans")
        await store_spans(session_factory, workspace.project_id, options, now)
        await build_rollups(session_factory, workspace.project_id, now)
        await vacuum_analyze(engine)
        await verify_and_report(engine, workspace.project_id, options.spans)
        write_credentials(options.credentials_file, workspace, data_end=now)
        say(f"credentials written to {options.credentials_file}")
    finally:
        await engine.dispose()


def main() -> None:
    options = parse_options(sys.argv[1:])
    # Deliberately not DATABASE_URL: a shell that points at a development database must not be
    # able to fill it with ten million spans by accident.
    database_url = os.environ.get("LOAD_DATABASE_URL", "")
    if not database_url:
        sys.exit("seed: set LOAD_DATABASE_URL to the owner URL of the database to fill")
    try:
        asyncio.run(run(options, database_url))
    except* (SeedError, WorkspaceError) as errors:
        # The workers run in a TaskGroup, which wraps their errors in a group. Exiting here would
        # wrap SystemExit in a group too, so only the message is taken and the exit comes after.
        failure = str(errors.exceptions[0])
    else:
        return
    sys.exit(f"seed: {failure}")


if __name__ == "__main__":
    main()
