// Runs after `astro build`. It does two things:
//
// 1. Checks that the built site is self-contained: no script, stylesheet, image, font or frame
//    comes from another origin, and no HTML attribute carries an inline event handler. The web
//    server's policy is `default-src 'self'`, so anything else would be blocked in the browser;
//    failing here finds it at build time.
//
// 2. Writes `.build/docs-csp.caddy`, the Caddy snippet that sets the Content-Security-Policy of
//    /docs/. The pages carry a few inline scripts (the theme switch, the copy buttons, hydration
//    of the search and table of contents). Instead of allowing every inline script with
//    'unsafe-inline', the policy allows exactly these scripts by their SHA-256 hash. The hashes
//    are computed from the built HTML on every build, so they cannot go stale.
//    'wasm-unsafe-eval' lets the search engine (Pagefind) instantiate its WebAssembly module; it
//    does not allow JavaScript eval. Styles keep 'unsafe-inline', as in the policy for the
//    dashboard.

import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(SITE, 'dist');
const OUT_DIR = path.join(SITE, '.build');

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(full) : [full];
  });
}

const files = walk(DIST);
const problems = [];
const hashes = new Set();

const isForeign = (url) => /^(https?:)?\/\//i.test(url);

for (const file of files.filter((f) => f.endsWith('.html'))) {
  const relative = path.relative(DIST, file);
  const html = fs.readFileSync(file, 'utf8');

  for (const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)) {
    const [, attributes, body] = match;
    const src = attributes.match(/\bsrc="([^"]*)"/i)?.[1];
    if (src !== undefined) {
      if (isForeign(src)) problems.push(`${relative}: script from another origin: ${src}`);
    } else if (body.trim() !== '') {
      hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
    }
  }
  for (const match of html.matchAll(/<(link|img|iframe|source|video|audio|embed|object)\b([^>]*)>/gi)) {
    const [, tag, attributes] = match;
    const rel = attributes.match(/\brel="([^"]*)"/i)?.[1] ?? '';
    // Links to other pages (rel="canonical", "alternate", "me") are navigation, not loads.
    if (tag.toLowerCase() === 'link' && !/stylesheet|preload|modulepreload|icon|prefetch/i.test(rel)) continue;
    const url = attributes.match(/\b(?:src|href|data)="([^"]*)"/i)?.[1];
    if (url && isForeign(url)) problems.push(`${relative}: <${tag}> loads another origin: ${url}`);
  }
  if (/\son[a-z]+\s*=\s*["']/i.test(html.replace(/<script\b[\s\S]*?<\/script>/gi, ''))) {
    problems.push(`${relative}: inline event handler attribute`);
  }
}

for (const file of files.filter((f) => /\.(css|js)$/.test(f) && !f.includes(`${path.sep}pagefind${path.sep}`))) {
  const text = fs.readFileSync(file, 'utf8');
  if (/@import\s+(url\()?["']?(https?:)?\/\//i.test(text) || /url\(\s*["']?(https?:)?\/\//i.test(text)) {
    problems.push(`${path.relative(DIST, file)}: stylesheet loads another origin`);
  }
}

if (problems.length > 0) {
  console.error('csp: the built site is not self-contained:');
  for (const problem of problems) console.error(`  ${problem}`);
  process.exit(1);
}

const policy = [
  "default-src 'self'",
  `script-src 'self' 'wasm-unsafe-eval' ${[...hashes].sort().join(' ')}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
].join('; ');

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(
  path.join(OUT_DIR, 'docs-csp.caddy'),
  `# Generated by docs-site/scripts/csp.mjs from the built pages. Do not edit.\nheader @docsSite Content-Security-Policy "${policy}"\n`,
);
console.log(`csp: site is self-contained; ${hashes.size} inline script hashes written to .build/docs-csp.caddy`);
